import Cocoa
import Quartz
import Vision
import PDFKit
import CryptoKit
import Carbon
import CoreServices
import UniformTypeIdentifiers

func featureError(_ message:String)->NSError { NSError(domain:"KongFetch",code:31,userInfo:[NSLocalizedDescriptionKey:message]) }
func fileIdentity(_ url:URL)->String? {
    guard let a=try? FileManager.default.attributesOfItem(atPath:url.path),let inode=a[.systemFileNumber] as? NSNumber,let device=a[.systemNumber] as? NSNumber else { return nil }; return "\(device):\(inode)"
}
func physicalURL(_ url:URL)->URL { if let path=realpath(url.path,nil) {defer {free(path)};return URL(fileURLWithPath:String(cString:path))};let parent=url.deletingLastPathComponent();guard parent.path != url.path else{return url.standardizedFileURL};return physicalURL(parent).appendingPathComponent(url.lastPathComponent) }
enum SearchPrecision:Int,CaseIterable {
    case exactName,fuzzyName,withPath
    var title:String { ["名称：精确","名称：模糊","名称及路径"][rawValue] }
    func score(_ url:URL,words:[String])->Int? {
        if words.isEmpty { return 0 }
        if self == .withPath { return filenameScore(url,words:words) }
        let name=url.lastPathComponent,stem=url.deletingPathExtension().lastPathComponent,phrase=normalized(words.joined(separator:" "))
        if normalized(name) == phrase || normalized(stem) == phrase { return 2000*words.count }
        if self == .exactName { return nil }
        var score=0; for word in words { if let s=fuzzyScore(name,word) { score += s+200 } else if let s=pinyinScore(pinyinForms(stem),word) { score += s } else { return nil } }; return score
    }
}
struct OCRGlyph:Codable { let location:Int; let length:Int; let x:Double; let y:Double; let width:Double; let height:Double; var rect:CGRect { CGRect(x:x,y:y,width:width,height:height) } }
struct OCRSpan:Codable {
    let page:Int; let text:String; let x:Double; let y:Double; let width:Double; let height:Double; let glyphs:[OCRGlyph]
    var rect:CGRect { CGRect(x:x,y:y,width:width,height:height) }
    func matches(_ words:[String])->[CGRect] {
        let ranges=matchRanges(text,words:words,allowWhitespace:true)
        return ranges.map { range in let boxes=glyphs.filter { NSIntersectionRange(NSRange(location:$0.location,length:$0.length),range).length > 0 }.map(\.rect); return boxes.reduce(CGRect.null) { $0.union($1) }.isNull ? rect : boxes.reduce(CGRect.null) { $0.union($1) } }
    }
}
func pdfBox(_ normalized:CGRect,on page:PDFPage)->CGRect {
    let media=page.bounds(for:.mediaBox),angle=((page.rotation%360)+360)%360
    func point(_ u:CGFloat,_ v:CGFloat)->CGPoint {
        switch angle { case 90:return CGPoint(x:media.minX+(1-v)*media.width,y:media.minY+u*media.height);case 180:return CGPoint(x:media.minX+(1-u)*media.width,y:media.minY+(1-v)*media.height);case 270:return CGPoint(x:media.minX+v*media.width,y:media.minY+(1-u)*media.height);default:return CGPoint(x:media.minX+u*media.width,y:media.minY+v*media.height) }
    }
    let points=[point(normalized.minX,normalized.minY),point(normalized.maxX,normalized.minY),point(normalized.minX,normalized.maxY),point(normalized.maxX,normalized.maxY)]
    let xs=points.map(\.x),ys=points.map(\.y);return CGRect(x:xs.min()!,y:ys.min()!,width:xs.max()!-xs.min()!,height:ys.max()!-ys.min()!)
}
func normalizedPDFBox(_ box:CGRect,on page:PDFPage)->CGRect {let media=page.bounds(for:.mediaBox);guard media.width > 0,media.height > 0 else{return .zero};let angle=((page.rotation%360)+360)%360;func point(_ x:CGFloat,_ y:CGFloat)->CGPoint {let u=(x-media.minX)/media.width,v=(y-media.minY)/media.height;switch angle {case 90:return CGPoint(x:v,y:1-u);case 180:return CGPoint(x:1-u,y:1-v);case 270:return CGPoint(x:1-v,y:u);default:return CGPoint(x:u,y:v)}};let points=[point(box.minX,box.minY),point(box.maxX,box.minY),point(box.minX,box.maxY),point(box.maxX,box.maxY)];let xs=points.map(\.x),ys=points.map(\.y);return CGRect(x:xs.min()!,y:ys.min()!,width:xs.max()!-xs.min()!,height:ys.max()!-ys.min()!)}
final class OCRImageView:NSView {
    var image:NSImage? { didSet { needsDisplay=true } };var boxes:[CGRect]=[] { didSet { needsDisplay=true } }
    override func draw(_ dirtyRect:NSRect) { super.draw(dirtyRect);guard let image,image.size.width > 0,image.size.height > 0 else { return };let scale=min(bounds.width/image.size.width,bounds.height/image.size.height);let frame=CGRect(x:(bounds.width-image.size.width*scale)/2,y:(bounds.height-image.size.height*scale)/2,width:image.size.width*scale,height:image.size.height*scale);image.draw(in:frame)
        for box in boxes { let r=CGRect(x:frame.minX+box.minX*frame.width,y:frame.minY+box.minY*frame.height,width:box.width*frame.width,height:box.height*frame.height);NSColor.systemYellow.withAlphaComponent(0.3).setFill();r.fill();NSColor.systemOrange.setStroke();let path=NSBezierPath(rect:r);path.lineWidth=1.5;path.stroke() }
    }
}
final class FolderWatcher {
    var stream:FSEventStreamRef?;var callback:([String],Bool)->Void
    init(_ callback:@escaping([String],Bool)->Void) { self.callback=callback }
    func start(_ roots:[URL]) {
        stop();guard !roots.isEmpty else { return };var context=FSEventStreamContext(version:0,info:Unmanaged.passUnretained(self).toOpaque(),retain:nil,release:nil,copyDescription:nil)
        stream=FSEventStreamCreate(nil,{ _,info,count,paths,flags,_ in guard let info else { return };let selfRef=Unmanaged<FolderWatcher>.fromOpaque(info).takeUnretainedValue(),strings=paths.assumingMemoryBound(to:UnsafePointer<CChar>.self);var result:[String]=[];var force=false
            for i in 0..<count { result.append(String(cString:strings[i]));if flags[i] & FSEventStreamEventFlags(kFSEventStreamEventFlagMustScanSubDirs|kFSEventStreamEventFlagUserDropped|kFSEventStreamEventFlagKernelDropped|kFSEventStreamEventFlagRootChanged) != 0 { force=true } };selfRef.callback(result,force)
        },&context,roots.map(\.path) as CFArray,FSEventStreamEventId(kFSEventStreamEventIdSinceNow),1,FSEventStreamCreateFlags(kFSEventStreamCreateFlagFileEvents|kFSEventStreamCreateFlagWatchRoot))
        if let stream { FSEventStreamSetDispatchQueue(stream,DispatchQueue.main);if !FSEventStreamStart(stream) { stop() } }
    }
    func stop() { if let stream { FSEventStreamStop(stream);FSEventStreamInvalidate(stream);FSEventStreamRelease(stream) };stream=nil }
    deinit { stop() }
}
struct OCRJob:Codable {
    var path:String;var state:String;var note:String;var updated:Date
}
final class OCRManager {
    let cacheWriteLock=NSLock()
    let store:OCRStore;let preferences:UserDefaults;let excludes:()->[String];let adaptive:()->Bool;let changed:([String:OCRRecord],String)->Void
    let scanQueue:OperationQueue={let q=OperationQueue();q.maxConcurrentOperationCount=1;q.qualityOfService = .utility;return q}()
    let queue:OperationQueue={let q=OperationQueue();q.maxConcurrentOperationCount=1;q.qualityOfService = .background;return q}()
    var records:[String:OCRRecord]=[:];var jobs:[String:OCRJob]=[:];var operations:[String:BlockOperation]=[:];var roots:[URL]=[];var identities:[String:String]=[:]
    var paused=false;var isScanning=false;var pending=Set<String>();var forceScan=false;var changeTimer:Timer?;var saveTimer:Timer?;var repairTimer:Timer?;var observer:(()->Void)?;var loaded=false;var stopped=false
    lazy var watcher=FolderWatcher { [weak self] paths,force in guard let self,!self.stopped else { return };let cache=physicalURL(self.store.directory).path;let exclusions=self.excludes().map{physicalURL(URL(fileURLWithPath:$0)).path};let filtered=paths.map{physicalURL(URL(fileURLWithPath:$0)).path}.filter {path in path != cache && !path.hasPrefix(cache+"/") && !exclusions.contains(where:{path == $0 || path.hasPrefix($0+"/")})};guard force || !filtered.isEmpty else{return};self.pending.formUnion(filtered);self.forceScan = self.forceScan || force;if self.changeTimer == nil {self.changeTimer=Timer.scheduledTimer(withTimeInterval:2,repeats:false) { [weak self] _ in self?.changeTimer=nil;self?.consumeChanges() }} }

    init(store:OCRStore,preferences:UserDefaults,excludes:@escaping()->[String],adaptive:@escaping()->Bool,changed:@escaping([String:OCRRecord],String)->Void) { self.store=store;self.preferences=preferences;self.excludes=excludes;self.adaptive=adaptive;self.changed=changed }
    var summary:String { let values=Array(jobs.values);return (paused ? "OCR 已暂停" : "OCR 自动更新")+" · \(values.filter{$0.state == "等待"}.count) 等待 · \(values.filter{$0.state == "识别中"}.count) 识别中 · \(values.filter{$0.state == "完成"}.count) 完成 · \(values.filter{$0.state == "失败"}.count) 失败"+(isScanning ? " · 正在检查目录" : "") }
    func emit() { guard !stopped else { return };changed(records,summary);observer?();saveTimer?.invalidate();saveTimer=Timer.scheduledTimer(withTimeInterval:1,repeats:false) { [weak self] _ in self?.saveJobs() } }
    var jobFile:URL { store.directory.appendingPathComponent("jobs-state.plist") }
    func saveJobs() { let snapshot=Array(jobs.values),url=jobFile;scanQueue.addOperation { try? FileManager.default.createDirectory(at:url.deletingLastPathComponent(),withIntermediateDirectories:true);if let data=try? PropertyListEncoder().encode(snapshot) { try? data.write(to:url,options:.atomic) } } }
    func resolveRoots() {
        let oldRoots=roots
        roots=(preferences.array(forKey:"ocrDirectories") as? [[String:Any]] ?? []).compactMap { item in
            if let data=item["bookmark"] as? Data { var stale=false;if let url=try? URL(resolvingBookmarkData:data,options:.withoutUI,relativeTo:nil,bookmarkDataIsStale:&stale) { return url } };return (item["path"] as? String).map { URL(fileURLWithPath:$0) }
        };roots=Array(Set(roots.map { physicalURL($0).standardizedFileURL })).sorted { $0.path < $1.path };saveRoots();if oldRoots != roots || watcher.stream == nil { watcher.start(roots.filter { FileManager.default.fileExists(atPath:$0.path) }) }
    }
    func saveRoots() { preferences.set(roots.map { url -> [String:Any] in var item:[String:Any]=["path":url.path];if let bookmark=try? url.bookmarkData(options:.minimalBookmark,includingResourceValuesForKeys:nil,relativeTo:nil) { item["bookmark"]=bookmark };return item },forKey:"ocrDirectories") }
    func start() {
        guard !loaded else { return };loaded=true;repairTimer=Timer.scheduledTimer(withTimeInterval:300,repeats:true) { [weak self] _ in guard let self,!self.stopped,!self.isScanning else{return};self.resolveRoots();for root in self.roots {self.scan(root)} };paused=preferences.bool(forKey:"ocrPaused");queue.isSuspended=paused;resolveRoots();let store=store,url=jobFile
        scanQueue.addOperation { [weak self] in let saved=store.load();let jobs=(try? Data(contentsOf:url)).flatMap { try? PropertyListDecoder().decode([OCRJob].self,from:$0) } ?? []
            DispatchQueue.main.async { guard let self,!self.stopped else { return };self.records=saved.merging(self.records,uniquingKeysWith:{ _,new in new });for job in jobs { self.jobs[job.path]=job };for record in self.records.values { if let identity=record.identity { self.identities[identity]=record.path };self.jobs[record.path]=OCRJob(path:record.path,state:record.isCurrent() ? "完成" : "待更新",note:record.spans == nil ? "旧版缓存，重新识别后可定位" : "\(record.pages) 页",updated:Date()) };self.emit();for root in self.roots { self.scan(root) } }
        }
    }
    func add(_ root:URL) { if !loaded { start() };let url=physicalURL(root).standardizedFileURL;if !roots.contains(url) { roots.append(url);saveRoots();watcher.start(roots) };scan(url) }
    func removeRoot(_ root:URL) { roots.removeAll { $0 == root };saveRoots();watcher.start(roots);for path in Array(operations.keys) where path == root.path || path.hasPrefix(root.path+"/") { operations.removeValue(forKey:path)?.cancel();jobs[path]?.state="已取消" };emit() }
    func eligible(_ url:URL)->Bool { let path=canonicalIndexPath(url);return !excludes().contains { let base=canonicalIndexPath(URL(fileURLWithPath:$0));return path == base || path.hasPrefix(base+"/") } && !path.hasPrefix(canonicalIndexPath(store.directory)+"/") && (FileFilter.pdf.accepts(Entry(url)) || FileFilter.images.accepts(Entry(url))) }
    func scan(_ root:URL) {
        let exclusions=excludes()+[store.directory.path],policy=ResourcePolicy(adaptive:adaptive());isScanning=true;emit();let operation=BlockOperation();operation.addExecutionBlock { [weak self,weak operation] in guard let operation else { return };let catalog=scanNames([root],excluding:exclusions,throttle:{ policy.pauseIfNeeded(cancelled:{operation.isCancelled}) },cancelled:{operation.isCancelled});let urls=catalog.urls.filter { FileFilter.pdf.accepts(Entry($0)) || FileFilter.images.accepts(Entry($0)) }
            DispatchQueue.main.async { guard let self,!self.stopped,!operation.isCancelled else { return };self.isScanning=false;if catalog.unreadable > 0 { self.jobs[root.path]=OCRJob(path:root.path,state:"失败",note:"目录不可访问，请连接磁盘或检查权限",updated:Date()) };for url in urls { self.enqueue(url) };self.emit() }
        };scanQueue.addOperation(operation)
    }
    func enqueue(_ url:URL,force:Bool=false) {
        guard !stopped,eligible(url) else { return };let path=url.path;guard operations[path] == nil else { pending.insert(path);return };let entry=Entry(url)
        if !force,let current=records[path],current.isCurrent(),current.spans != nil { jobs[path]=OCRJob(path:path,state:"完成",note:"\(current.pages) 页 · 缓存有效",updated:Date());return }
        if !force,let identity=fileIdentity(url),let oldPath=identities[identity],oldPath != path,let old=records[oldPath],old.size == entry.size,old.modified == entry.modified,old.spans != nil {
            let moved=OCRRecord(path:path,modified:old.modified,size:old.size,text:old.text,pages:old.pages,limited:old.limited,spans:old.spans,identity:identity);records.removeValue(forKey:oldPath);records[path]=moved;identities[identity]=path;jobs.removeValue(forKey:oldPath);jobs[path]=OCRJob(path:path,state:"完成",note:"已跟随文件移动",updated:Date());scanQueue.addOperation { [store] in try? store.remove(oldPath);try? store.save(moved) };emit();return
        }
        guard jobs.count < 25000 || jobs[path] != nil else { jobs["__limit__"]=OCRJob(path:"__limit__",state:"失败",note:"已达到 25000 个任务，请清理失效记录后继续",updated:Date());return }
        jobs[path]=OCRJob(path:path,state:"等待",note:paused ? "暂停后继续处理" : "",updated:Date());let policy=ResourcePolicy(adaptive:adaptive()),store=store,operation=BlockOperation();operations[path]=operation
        operation.addExecutionBlock { [weak self,weak operation] in guard let operation else { return };if operation.isCancelled { return };policy.pauseIfNeeded(cancelled:{ operation.isCancelled });if operation.isCancelled { return }
            DispatchQueue.main.async { guard let self,self.operations[path] === operation else { return };self.jobs[path]?.state="识别中";self.emit() }
            do { let record=try autoreleasepool { try recognizeLocalText(url,cancelled:{operation.isCancelled},progress:{ page in DispatchQueue.main.async { guard let self,self.operations[path] === operation else { return };self.jobs[path]?.note="第 \(page) 页";self.observer?() } }) };if operation.isCancelled { return };guard record.isCurrent() else { throw featureError("识别时文件发生变化，将重新检查") };try { self?.cacheWriteLock.lock();defer {self?.cacheWriteLock.unlock()};guard !operation.isCancelled else {throw featureError("已取消")};try store.save(record) }()
                DispatchQueue.main.async { guard let self,!self.stopped,self.operations[path] === operation else { return };self.operations.removeValue(forKey:path);self.records[path]=record;if let identity=record.identity { self.identities[identity]=path };self.jobs[path]=OCRJob(path:path,state:"完成",note:"\(record.pages) 页"+(record.limited ? " · 达到页数或长度限制" : ""),updated:Date());self.emit();if self.pending.remove(path) != nil { self.enqueue(url) } }
            } catch { DispatchQueue.main.async { guard let self,!self.stopped,self.operations[path] === operation else { return };self.operations.removeValue(forKey:path);self.jobs[path]=OCRJob(path:path,state:"失败",note:error.localizedDescription,updated:Date());self.emit();if self.pending.remove(path) != nil || error.localizedDescription.contains("文件发生变化") { self.enqueue(url) } } }
        };queue.addOperation(operation);emit()
    }
    func consumeChanges() {
        let paths=Array(pending);pending=[];let force=forceScan;forceScan=false;resolveRoots()
        if force { for root in roots { scan(root) };return }
        for path in paths {
            let url=URL(fileURLWithPath:path);guard roots.contains(where:{path == $0.path || path.hasPrefix($0.path+"/")}) else { continue }
            if !FileManager.default.fileExists(atPath:path) { for old in Array(records.keys) where old == path || old.hasPrefix(path+"/") { records.removeValue(forKey:old);jobs[old]?.state="待更新";jobs[old]?.note="文件已移动或删除";scanQueue.addOperation { [store] in try? store.remove(old) } };continue }
            if Entry(url).directory { scan(url) } else { enqueue(url) }
        };emit()
    }
    func setPaused(_ value:Bool) { paused=value;queue.isSuspended=value;preferences.set(value,forKey:"ocrPaused");if !value { if jobs.isEmpty { for root in roots { scan(root) } };for (path,job) in jobs where job.state == "已取消" || job.state == "待更新" { enqueue(URL(fileURLWithPath:path)) } };emit() }
    func cancel() { cacheWriteLock.lock();for (path,op) in operations { op.cancel();jobs[path]?.state="已取消" };operations=[:];cacheWriteLock.unlock();setPaused(true) }
    func retryFailures() { for (path,job) in jobs where job.state == "失败" { let url=URL(fileURLWithPath:path);if Entry(url).directory { scan(url) } else { enqueue(url,force:true) } };setPaused(false) }
    func cleanStale() { let paths=records.keys.filter { !records[$0]!.isCurrent() };for path in paths { records.removeValue(forKey:path);jobs.removeValue(forKey:path);scanQueue.addOperation { [store] in try? store.remove(path) } };jobs=jobs.filter { $0.key == "__limit__" ? false : FileManager.default.fileExists(atPath:$0.key) };emit() }
    func clear() { cancel();records=[:];jobs=[:];identities=[:];scanQueue.addOperation { [store] in try? store.clear() };emit() }
    func stop(wait:Bool=false) { stopped=true;watcher.stop();repairTimer?.invalidate();changeTimer?.invalidate();saveTimer?.invalidate();queue.isSuspended=false;queue.cancelAllOperations();scanQueue.cancelAllOperations();if wait { queue.waitUntilAllOperationsAreFinished();scanQueue.waitUntilAllOperationsAreFinished() } }
}

struct ZipMember {
    let archive:URL;let name:String;let size:UInt32;let compressed:UInt32;let crc:UInt32;let method:UInt16;let flags:UInt16;let attributes:UInt32;let localOffset:UInt32
    var directory:Bool { name.hasSuffix("/") }
    var symlink:Bool { (attributes >> 16) & 0xf000 == 0xa000 }
    var basename:String { URL(fileURLWithPath:name).lastPathComponent }
    var safe:Bool { !name.isEmpty && !name.hasPrefix("/") && !name.contains("\\") && !name.contains(":") && !name.unicodeScalars.contains(where:{ $0.value < 32 }) && !name.split(separator:"/",omittingEmptySubsequences:false).contains("..") }
}
struct ZipListing { let members:[ZipMember];let modified:Date?;let size:Int64 }
func listZIP(_ url:URL)throws->ZipListing {
    let entry=Entry(url);guard entry.size >= 22 else { throw featureError("不是有效的 ZIP") };let handle=try FileHandle(forReadingFrom:url);defer { try? handle.close() };let offset=UInt64(max(0,entry.size-65557));try handle.seek(toOffset:offset);let tail=try handle.readToEnd() ?? Data()
    func u16(_ data:Data,_ at:Int)->UInt16 { UInt16(data[at]) | UInt16(data[at+1])<<8 };func u32(_ data:Data,_ at:Int)->UInt32 { UInt32(u16(data,at)) | UInt32(u16(data,at+2))<<16 }
    var eocd:Int?;if tail.count >= 22 { for i in stride(from:tail.count-22,through:0,by:-1) where u32(tail,i) == 0x06054b50 { if i+22+Int(u16(tail,i+20)) == tail.count { eocd=i;break } } };guard let eocd else { throw featureError("ZIP 目录损坏或需要 ZIP64，暂不支持") }
    guard u16(tail,eocd+4) == 0,u16(tail,eocd+6) == 0,u16(tail,eocd+8) == u16(tail,eocd+10) else { throw featureError("暂不支持分卷 ZIP") }
    let count=Int(u16(tail,eocd+10)),length=Int(u32(tail,eocd+12)),start=UInt64(u32(tail,eocd+16));guard count < 65535,length <= 50_000_000,start+UInt64(length) <= offset+UInt64(eocd) else { throw featureError("ZIP64 或超大目录暂不支持") };try handle.seek(toOffset:start);let data=try handle.read(upToCount:length) ?? Data();guard data.count == length else { throw featureError("ZIP 目录不完整") }
    var cursor=0,members:[ZipMember]=[]
    for _ in 0..<count { guard cursor+46 <= data.count,u32(data,cursor) == 0x02014b50 else { throw featureError("ZIP 目录项损坏") };let nameSize=Int(u16(data,cursor+28)),extra=Int(u16(data,cursor+30)),comment=Int(u16(data,cursor+32)),end=cursor+46+nameSize+extra+comment;guard end <= data.count else { throw featureError("ZIP 名称损坏") };let bytes=data.subdata(in:cursor+46..<cursor+46+nameSize);let name=String(data:bytes,encoding:.utf8) ?? String(data:bytes,encoding:.isoLatin1) ?? "";let member=ZipMember(archive:url,name:name,size:u32(data,cursor+24),compressed:u32(data,cursor+20),crc:u32(data,cursor+16),method:u16(data,cursor+10),flags:u16(data,cursor+8),attributes:u32(data,cursor+38),localOffset:u32(data,cursor+42));members.append(member);cursor=end }
    return ZipListing(members:members,modified:entry.modified,size:entry.size)
}
func extractZIPMember(_ member:ZipMember,to directory:URL,cancelled:()->Bool={false})throws->URL {
    guard member.safe,!member.directory,!member.symlink,member.flags & 1 == 0,[0,8].contains(member.method),member.size <= 100_000_000 else { throw featureError("此项是目录、链接、加密文件、超大文件或使用不支持的压缩方式") }
    let current=try listZIP(member.archive);guard current.members.contains(where:{$0.name == member.name && $0.crc == member.crc && $0.size == member.size && $0.flags == member.flags && $0.localOffset == member.localOffset}) else {throw featureError("压缩包已变化，请重新搜索")};try FileManager.default.createDirectory(at:directory,withIntermediateDirectories:true);let unique=directory.appendingPathComponent(UUID().uuidString);try FileManager.default.createDirectory(at:unique,withIntermediateDirectories:true);let destination=unique.appendingPathComponent(member.basename);guard !FileManager.default.fileExists(atPath:destination.path) else { throw featureError("预览目标已存在") };FileManager.default.createFile(atPath:destination.path,contents:nil);let output=try FileHandle(forWritingTo:destination);defer { try? output.close() }
    let pattern=member.name.map { "*?[]\\".contains($0) ? "\\"+String($0) : String($0) }.joined();let process=Process(),pipe=Pipe();process.executableURL=URL(fileURLWithPath:"/usr/bin/unzip");process.arguments=["-p",member.archive.path,pattern];process.standardOutput=pipe;process.standardError=FileHandle.nullDevice
    do { try process.run();var bytes=0;while let data=try pipe.fileHandleForReading.read(upToCount:65536),!data.isEmpty { if cancelled() || bytes+data.count > 100_000_000 { process.terminate();throw featureError("已取消或解压超过 100 MB") };try output.write(contentsOf:data);bytes += data.count };process.waitUntilExit();guard process.terminationStatus == 0,bytes == Int(member.size) else { throw featureError("解压失败、文件名编码不支持或 ZIP 校验未通过") };return destination }
    catch { if process.isRunning { process.terminate();process.waitUntilExit() };try? FileManager.default.removeItem(at:destination);throw error }
}

struct RenameRule {
    var prefix="",suffix="",find="",replacement="",numbered=false,start=1,digits=3
    func name(_ url:URL,index:Int)->String { let isDirectory=Entry(url).directory,ext=isDirectory ? "" : url.pathExtension,stem=isDirectory || ext.isEmpty ? url.lastPathComponent : url.deletingPathExtension().lastPathComponent;let changed=find.isEmpty ? stem : stem.replacingOccurrences(of:find,with:replacement);let number=numbered ? "-"+String(format:"%0*d",min(9,max(1,digits)),max(0,min(1_000_000_000,start))+index) : "";return prefix+changed+suffix+number+(ext.isEmpty ? "" : "."+ext) }
}
struct RenamePair:Codable { let original:String;let target:String;let identity:String;let temporary:String }
struct RenameJournal:Codable { let items:[RenamePair];var completed:Bool }
enum BatchRename {
    static func plan(_ urls:[URL],rule:RenameRule)throws->[(URL,URL)] {
        guard !urls.isEmpty,urls.count <= 500 else { throw featureError("请选择 1–500 个文件或文件夹") };var pairs:[(URL,URL)]=[]
        for (index,url) in urls.enumerated() { let name=rule.name(url,index:index);guard !name.isEmpty,name != ".",name != "..",!name.contains("/"),!name.contains(":"),!name.contains("\\"),name.utf8.count <= 255 else { throw featureError("无效名称："+name) };let target=url.deletingLastPathComponent().appendingPathComponent(name);if url.path != target.path { pairs.append((url,target)) } };try validate(pairs);return pairs
    }
    static func key(_ url:URL)->String { url.standardizedFileURL.path.precomposedStringWithCanonicalMapping.lowercased() }
    static func validate(_ pairs:[(URL,URL)])throws {
        let source=Set(pairs.map{key($0.0)});guard source.count == pairs.count,Set(pairs.map{key($0.1)}).count == pairs.count else { throw featureError("名称重复或大小写冲突") }
        for (url,target) in pairs { guard FileManager.default.fileExists(atPath:url.path) else { throw featureError("原文件已不存在："+url.lastPathComponent) };if FileManager.default.fileExists(atPath:target.path),!source.contains(key(target)) { throw featureError("目标已存在，不会覆盖："+target.lastPathComponent) };if pairs.contains(where:{ $0.0.path != url.path && url.path.hasPrefix($0.0.path+"/") }) { throw featureError("请分别重命名父目录及其内部文件") } }
    }
    static func execute(_ pairs:[(URL,URL)],journalDirectory:URL)throws {
        if pairs.isEmpty { return };try validate(pairs);try FileManager.default.createDirectory(at:journalDirectory,withIntermediateDirectories:true);let journalURL=journalDirectory.appendingPathComponent(UUID().uuidString+".json"),items=try pairs.map { original,target -> RenamePair in guard let identity=fileIdentity(original) else { throw featureError("无法确认文件身份") };return RenamePair(original:original.path,target:target.path,identity:identity,temporary:original.deletingLastPathComponent().appendingPathComponent(".kongfetch-rename-"+UUID().uuidString).path) };let journal=RenameJournal(items:items,completed:false);try JSONEncoder().encode(journal).write(to:journalURL,options:.atomic)
        var stage1:[RenamePair]=[],stage2:[RenamePair]=[]
        do { for item in items { try FileManager.default.moveItem(atPath:item.original,toPath:item.temporary);stage1.append(item) };for item in items { guard !FileManager.default.fileExists(atPath:item.target) else { throw featureError("操作期间目标被占用："+item.target) };try FileManager.default.moveItem(atPath:item.temporary,toPath:item.target);stage2.append(item) };try FileManager.default.removeItem(at:journalURL) }
        catch { var restored=true;for item in stage2.reversed() { do { try FileManager.default.moveItem(atPath:item.target,toPath:item.temporary) } catch { restored=false } };for item in stage1.reversed() { do { guard !FileManager.default.fileExists(atPath:item.original) else { throw featureError("原位置被占用") };try FileManager.default.moveItem(atPath:item.temporary,toPath:item.original) } catch { restored=false } };if restored { try? FileManager.default.removeItem(at:journalURL) };throw featureError(error.localizedDescription+(restored ? "；已恢复原名称" : "；部分恢复失败，请通过批量重命名恢复记录处理")) }
    }
    static func recoveryPairs(_ url:URL)throws->[(URL,URL)] {
        let data=try Data(contentsOf:url);guard data.count <= 1_000_000 else { throw featureError("恢复记录过大") };let journal=try JSONDecoder().decode(RenameJournal.self,from:data);guard journal.items.count <= 500 else { throw featureError("恢复记录无效") }
        return try journal.items.compactMap { item in guard let current=[item.temporary,item.target,item.original].first(where:{ fileIdentity(URL(fileURLWithPath:$0)) == item.identity }) else { throw featureError("无法找到原文件："+item.original) };if current == item.original { return nil };return (URL(fileURLWithPath:current),URL(fileURLWithPath:item.original)) }
    }
}

struct UpdateManifest:Codable {
    let version:String;let build:Int;let minimumSystemVersion:String;let notes:[String];let zipURL:String;let sha256:String;let bytes:Int
    func validate()throws {
        guard version.count <= 40,minimumSystemVersion.count <= 20,version.split(separator:".").allSatisfy({ Int($0) != nil }),version.range(of:"^[0-9]+(?:\\.[0-9]+){1,3}$",options:.regularExpression) != nil,minimumSystemVersion.range(of:"^[0-9]+(?:\\.[0-9]+){0,2}$",options:.regularExpression) != nil,build > 0,notes.count <= 30,notes.allSatisfy({$0.count <= 1000}),sha256.range(of:"^[a-fA-F0-9]{64}$",options:.regularExpression) != nil,bytes > 0,bytes <= 100_000_000,let url=URL(string:zipURL),trustedUpdateURL(url) else { throw featureError("更新清单无效，未下载安装") }
    }
}
func versionOrder(_ a:String,_ b:String)->ComparisonResult {
    let lhs=a.split(separator:".").map { Int($0) ?? 0 },rhs=b.split(separator:".").map { Int($0) ?? 0 };for i in 0..<max(lhs.count,rhs.count) { let x=i<lhs.count ? lhs[i] : 0,y=i<rhs.count ? rhs[i] : 0;if x != y { return x > y ? .orderedDescending : .orderedAscending } };return .orderedSame
}
func trustedUpdateURL(_ url:URL)->Bool {
    guard url.scheme == "https",url.user == nil,url.password == nil else { return false }
    switch url.host?.lowercased() { case "raw.githubusercontent.com":return url.path.hasPrefix("/kongxiangruihello/KongFetch/");case "github.com":return url.path.hasPrefix("/kongxiangruihello/KongFetch/");default:return false }
}
func githubRedirectURL(_ url:URL)->Bool { guard url.scheme == "https",url.user == nil,url.password == nil else { return false };return trustedUpdateURL(url) || url.host == "release-assets.githubusercontent.com" || url.host == "objects.githubusercontent.com" }
func sha256File(_ url:URL,maxBytes:Int64=100_000_000)throws->String {
    let stream=try FileHandle(forReadingFrom:url);defer {try? stream.close()};var hash=SHA256(),size:Int64=0;while let data=try stream.read(upToCount:262144),!data.isEmpty { size += Int64(data.count);guard size <= maxBytes else { throw featureError("安装包超过允许大小") };hash.update(data:data) };return hash.finalize().map {String(format:"%02x",$0)}.joined()
}
final class UpdateDownload:NSObject,URLSessionDownloadDelegate,URLSessionTaskDelegate,@unchecked Sendable {
    let manifest:UpdateManifest;let destination:URL;let progress:(Double)->Void;let completion:(Result<URL,Error>)->Void;var session:URLSession?;var finished=false
    init(manifest:UpdateManifest,destination:URL,progress:@escaping(Double)->Void,completion:@escaping(Result<URL,Error>)->Void) { self.manifest=manifest;self.destination=destination;self.progress=progress;self.completion=completion }
    func start() { let config=URLSessionConfiguration.ephemeral;config.timeoutIntervalForRequest=30;config.timeoutIntervalForResource=600;config.httpCookieStorage=nil;config.urlCredentialStorage=nil;session=URLSession(configuration:config,delegate:self,delegateQueue:nil);session!.downloadTask(with:URL(string:manifest.zipURL)!).resume() }
    func finish(_ result:Result<URL,Error>) { guard !finished else { return };finished=true;DispatchQueue.main.async { self.completion(result) };session?.finishTasksAndInvalidate();session=nil }
    func urlSession(_ session:URLSession,task:URLSessionTask,willPerformHTTPRedirection response:HTTPURLResponse,newRequest request:URLRequest,completionHandler:@escaping(URLRequest?)->Void) { completionHandler(request.url.map(githubRedirectURL) == true ? request : nil) }
    func urlSession(_ session:URLSession,downloadTask:URLSessionDownloadTask,didWriteData bytesWritten:Int64,totalBytesWritten:Int64,totalBytesExpectedToWrite:Int64) { if totalBytesWritten > Int64(manifest.bytes) || totalBytesWritten > 100_000_000 { downloadTask.cancel() };let value=Double(totalBytesWritten)/Double(manifest.bytes);DispatchQueue.main.async {self.progress(min(1,value))} }
    func urlSession(_ session:URLSession,downloadTask:URLSessionDownloadTask,didFinishDownloadingTo location:URL) {
        do { guard let response=downloadTask.response as? HTTPURLResponse,response.statusCode == 200,let url=response.url,githubRedirectURL(url) else {throw featureError("安装包下载未通过来源检查")};let size=(try location.resourceValues(forKeys:[.fileSizeKey])).fileSize ?? 0;guard size == manifest.bytes,try sha256File(location) == manifest.sha256.lowercased() else {throw featureError("安装包大小或 SHA-256 不匹配，未安装")};try FileManager.default.createDirectory(at:destination.deletingLastPathComponent(),withIntermediateDirectories:true);try FileManager.default.moveItem(at:location,to:destination);finish(.success(destination)) } catch {finish(.failure(error))}
    }
    func urlSession(_ session:URLSession,task:URLSessionTask,didCompleteWithError error:Error?) { if let error { finish(.failure(error)) } }
    func cancel() { session?.invalidateAndCancel() }
}
func runTool(_ executable:String,_ arguments:[String])throws {
    let process=Process();process.executableURL=URL(fileURLWithPath:executable);process.arguments=arguments;process.standardOutput=FileHandle.nullDevice;process.standardError=FileHandle.nullDevice;try process.run();process.waitUntilExit();guard process.terminationStatus == 0 else {throw featureError("处理失败："+URL(fileURLWithPath:executable).lastPathComponent)}
}
enum ApplicationInstaller {
    static func version(_ app:URL)throws->String {
        guard !((try app.resourceValues(forKeys:[.isSymbolicLinkKey])).isSymbolicLink ?? false),let data=try? Data(contentsOf:app.appendingPathComponent("Contents/Info.plist")),let values=try? PropertyListSerialization.propertyList(from:data,format:nil) as? [String:Any],values["CFBundleIdentifier"] as? String == "com.kongfetch.mac",values["CFBundleExecutable"] as? String == "KongFetch",let version=values["CFBundleShortVersionString"] as? String else {throw featureError("不是有效的 KongFetch 应用")};let binary=app.appendingPathComponent("Contents/MacOS/KongFetch");guard !((try binary.resourceValues(forKeys:[.isSymbolicLinkKey])).isSymbolicLink ?? false) else {throw featureError("应用程序入口不允许是符号链接")};let current=ProcessInfo.processInfo.operatingSystemVersion;let os="\(current.majorVersion).\(current.minorVersion).\(current.patchVersion)";guard versionOrder(values["LSMinimumSystemVersion"] as? String ?? "13.0",os) != .orderedDescending else {throw featureError("当前 macOS 版本不满足新版要求")};try runTool("/usr/bin/codesign",["--verify","--deep","--strict",app.path]);return version
    }
    static func prepare(_ zip:URL,manifest:UpdateManifest,directory:URL)throws->URL {
        try manifest.validate();guard try sha256File(zip) == manifest.sha256.lowercased(),Entry(zip).size == Int64(manifest.bytes) else {throw featureError("安装包校验不匹配")};let listing=try listZIP(zip);guard !listing.members.isEmpty,listing.members.count < 10000,listing.members.reduce(Int64(0),{$0+Int64($1.size)}) <= 250_000_000 else {throw featureError("安装包展开体积或文件数异常")}
        let keys=listing.members.map { $0.name.trimmingCharacters(in:CharacterSet(charactersIn:"/")).precomposedStringWithCanonicalMapping.lowercased() };guard Set(keys).count == keys.count else {throw featureError("安装包包含重复路径")};let links=listing.members.filter(\.symlink);for item in listing.members { guard item.safe,item.flags & 1 == 0 else {throw featureError("安装包包含不安全路径或加密内容")};if item.symlink { guard item.basename == "Applications",item.name.split(separator:"/").count <= 2,item.size <= 4096 else {throw featureError("安装包包含不允许的符号链接")} };guard !links.contains(where:{$0.name != item.name && item.name.hasPrefix($0.name+"/")}) else {throw featureError("安装包在符号链接下包含文件")} }
        guard !FileManager.default.fileExists(atPath:directory.path) else {throw featureError("更新暂存目录已存在")};try FileManager.default.createDirectory(at:directory,withIntermediateDirectories:true);try runTool("/usr/bin/ditto",["-x","-k",zip.path,directory.path]);for link in links {let extracted=directory.appendingPathComponent(link.name);guard (try FileManager.default.destinationOfSymbolicLink(atPath:extracted.path)) == "/Applications" else {throw featureError("安装包的应用程序快捷链接无效")}};let enumerator=FileManager.default.enumerator(at:directory,includingPropertiesForKeys:[.isDirectoryKey],options:[.skipsHiddenFiles,.skipsPackageDescendants]);var apps:[URL]=[];while let url=enumerator?.nextObject() as? URL { if url.pathExtension == "app",url.lastPathComponent == "KongFetch.app" {apps.append(url);enumerator?.skipDescendants()} };guard apps.count == 1 else {throw featureError("安装包必须包含一个 KongFetch.app")};let app=apps[0];guard try version(app) == manifest.version else {throw featureError("应用版本与更新清单不一致")};return app
    }
    static func install(_ source:URL,target:URL,backupDirectory:URL)throws->URL {
        let newVersion=try version(source),oldVersion=try version(target);guard source.standardizedFileURL != target.standardizedFileURL,let identity=fileIdentity(target) else {throw featureError("更新来源或目标无效")};let fm=FileManager.default,parent=target.deletingLastPathComponent(),staged=parent.appendingPathComponent(".KongFetch-new-"+UUID().uuidString+".app"),old=parent.appendingPathComponent(".KongFetch-old-"+UUID().uuidString+".app");try fm.createDirectory(at:backupDirectory,withIntermediateDirectories:true);let backup=backupDirectory.appendingPathComponent("KongFetch-"+oldVersion+"-"+UUID().uuidString+".app")
        try fm.copyItem(at:source,to:staged);defer {try? fm.removeItem(at:staged)};guard try version(staged) == newVersion else {throw featureError("暂存应用检查失败")};try fm.copyItem(at:target,to:backup);guard try version(backup) == oldVersion,fileIdentity(target) == identity else {throw featureError("备份检查失败或目标应用已变化，停止更新")};try fm.moveItem(at:target,to:old)
        do {try fm.moveItem(at:staged,to:target)} catch {if !fm.fileExists(atPath:target.path) {try? fm.moveItem(at:old,to:target)};throw error};try? fm.removeItem(at:old);return backup
    }
}
func runInstallHelper(_ args:[String])throws {
    guard args.count == 7,let pid=Int32(args[2]),pid > 1 else {throw featureError("更新参数无效")};let source=URL(fileURLWithPath:args[3]),target=URL(fileURLWithPath:args[4]),backups=URL(fileURLWithPath:args[5]),report=URL(fileURLWithPath:args[6]);let approved=["/Applications/KongFetch.app",NSHomeDirectory()+"/Applications/KongFetch.app"]
    guard report.path == NSHomeDirectory()+"/Library/Application Support/KongFetch/Updates/last-result.json",approved.contains(target.path),backups.path == NSHomeDirectory()+"/Library/Application Support/KongFetch/Updates/Backups",source.resolvingSymlinksInPath().path.hasPrefix(NSHomeDirectory()+"/Library/Application Support/KongFetch/Updates/") else {throw featureError("更新路径不允许")}
    for _ in 0..<400 {if kill(pid,0) != 0 {break};Thread.sleep(forTimeInterval:0.05)};guard kill(pid,0) != 0 else {throw featureError("旧版应用未退出，请手动关闭后重新安装")}
    do {let backup=try ApplicationInstaller.install(source,target:target,backupDirectory:backups);try JSONSerialization.data(withJSONObject:["ok":true,"version":ApplicationInstaller.version(target),"backup":backup.path,"message":"更新完成，请检查输入监控授权和双 Control 唤起"]).write(to:report,options:.atomic);_ = NSWorkspace.shared.open(target)} catch {try? JSONSerialization.data(withJSONObject:["ok":false,"message":error.localizedDescription]).write(to:report,options:.atomic);_ = NSWorkspace.shared.open(target);throw error}
}

// Shared native auxiliary windows keep the search window at 750 × 474 points.
func featurePanel(_ title:String,size:NSSize=NSSize(width:780,height:540))->NSPanel {
    let panel=NSPanel(contentRect:NSRect(origin:.zero,size:size),styleMask:[.titled,.closable,.resizable],backing:.buffered,defer:false);panel.title=title;panel.isReleasedWhenClosed=false;panel.minSize=NSSize(width:640,height:420);panel.center();return panel
}
func featureStack(_ views:[NSView],vertical:Bool=false)->NSStackView { let stack=NSStackView(views:views);stack.orientation=vertical ? .vertical : .horizontal;stack.alignment = vertical ? .leading : .centerY;stack.spacing=10;return stack }
func featureMount(_ stack:NSStackView,in panel:NSWindow) { let root=panel.contentView!;stack.translatesAutoresizingMaskIntoConstraints=false;root.addSubview(stack);NSLayoutConstraint.activate([stack.leadingAnchor.constraint(equalTo:root.leadingAnchor,constant:18),stack.trailingAnchor.constraint(equalTo:root.trailingAnchor,constant:-18),stack.topAnchor.constraint(equalTo:root.topAnchor,constant:18),stack.bottomAnchor.constraint(equalTo:root.bottomAnchor,constant:-18)]) }
func featureTable(_ columns:[(String,String,CGFloat)],target:AnyObject)->(NSTableView,NSScrollView) { let table=NSTableView();for (id,title,width) in columns { let c=NSTableColumn(identifier:NSUserInterfaceItemIdentifier(id));c.title=title;c.width=width;table.addTableColumn(c) };table.rowHeight=36;table.usesAlternatingRowBackgroundColors=true;table.delegate=target as? NSTableViewDelegate;table.dataSource=target as? NSTableViewDataSource;let scroll=NSScrollView();scroll.hasVerticalScroller=true;scroll.hasHorizontalScroller=true;scroll.documentView=table;return (table,scroll) }
func featureCell(_ text:String)->NSTextField { let field=NSTextField(labelWithString:text);field.lineBreakMode = .byTruncatingMiddle;field.toolTip=text;return field }
func featureButton(_ title:String,_ target:AnyObject,_ selector:Selector)->NSButton { let b=NSButton(title:title,target:target,action:selector);b.bezelStyle = .rounded;return b }
func featureNotice(_ window:NSWindow,_ text:String) { let alert=NSAlert();alert.messageText=text;alert.beginSheetModal(for:window) }

final class OCRPanelController:NSObject,NSTableViewDataSource,NSTableViewDelegate,NSSearchFieldDelegate {
    let manager:OCRManager;let panel=featurePanel("OCR 管理");var table:NSTableView!;let query=NSSearchField();let roots=NSPopUpButton();let state=NSTextField(wrappingLabelWithString:"");var pause:NSButton!;var rows:[OCRJob]=[]
    init(_ manager:OCRManager) { self.manager=manager;super.init();let pair=featureTable([("name","文件",340),("state","状态",80),("note","进度 / 原因",280)],target:self);table=pair.0;query.placeholderString="筛选文件或状态";query.delegate=self;roots.widthAnchor.constraint(lessThanOrEqualToConstant:480).isActive=true;roots.cell?.lineBreakMode = .byTruncatingMiddle;pause=featureButton("暂停",self,#selector(togglePause));let header=featureStack([featureButton("添加目录…",self,#selector(add)),roots,featureButton("移除目录",self,#selector(remove))]);let controls=featureStack([pause,featureButton("重试失败",self,#selector(retry)),featureButton("清理失效缓存",self,#selector(clean)),featureButton("清空缓存…",self,#selector(clear)),featureButton("查看原文件",self,#selector(reveal))]);let stack=featureStack([header,query,state,pair.1,controls],vertical:true);featureMount(stack,in:panel);for view in [header,query,state,pair.1,controls] { view.widthAnchor.constraint(equalTo:stack.widthAnchor).isActive=true };pair.1.heightAnchor.constraint(greaterThanOrEqualToConstant:240).isActive=true;query.heightAnchor.constraint(equalToConstant:26).isActive=true;manager.observer={ [weak self] in self?.refresh() };manager.start();refresh() }
    func show() { refresh();panel.makeKeyAndOrderFront(nil) }
    func refresh() { let selected=roots.selectedItem?.title;roots.removeAllItems();roots.addItems(withTitles:manager.roots.map { $0.lastPathComponent });for (i,root) in manager.roots.enumerated(){roots.item(at:i)?.toolTip=root.path};if let selected {roots.selectItem(withTitle:selected)};pause.title=manager.paused ? "继续" : "暂停";state.stringValue=manager.summary+"\n仅识别所选目录，文字保存在本机。暂停后当前文件会处理完；新增与修改文件自动更新。";let text=normalized(query.stringValue);rows=manager.jobs.values.filter { text.isEmpty || normalized($0.path+" "+$0.state+" "+$0.note).contains(text) }.sorted { if $0.state != $1.state { return $0.state < $1.state };return $0.path.localizedStandardCompare($1.path) == .orderedAscending };table.reloadData() }
    func controlTextDidChange(_ obj:Notification) { refresh() }
    func numberOfRows(in tableView:NSTableView)->Int { rows.count }
    func tableView(_ tableView:NSTableView,viewFor column:NSTableColumn?,row:Int)->NSView? { let job=rows[row];return featureCell(column?.identifier.rawValue == "name" ? (job.path as NSString).abbreviatingWithTildeInPath : column?.identifier.rawValue == "state" ? job.state : job.note) }
    @objc func add() { let p=NSOpenPanel();p.canChooseFiles=false;p.canChooseDirectories=true;p.allowsMultipleSelection=true;p.beginSheetModal(for:panel) { [weak self] response in guard let self,response == .OK else {return};for url in p.urls {self.manager.add(url)} } }
    @objc func remove() { guard roots.indexOfSelectedItem >= 0 else {return};manager.removeRoot(manager.roots[roots.indexOfSelectedItem]) }
    @objc func togglePause() { manager.setPaused(!manager.paused) }
    @objc func retry() { manager.retryFailures() }
    @objc func clean() {manager.cleanStale()}
    @objc func clear() { let a=NSAlert();a.messageText="清空 OCR 文字缓存？";a.informativeText="原文件保留，自动识别将暂停。点击继续后会重新建立缓存。";a.addButton(withTitle:"清空");a.addButton(withTitle:"取消");a.beginSheetModal(for:panel) { [weak self] response in if response == .alertFirstButtonReturn {self?.manager.clear()} } }
    @objc func reveal() {guard rows.indices.contains(table.selectedRow) else{return};NSWorkspace.shared.activateFileViewerSelecting([URL(fileURLWithPath:rows[table.selectedRow].path)])}
}
final class ArchiveSearchController:NSObject,NSTableViewDataSource,NSTableViewDelegate,NSSearchFieldDelegate {
    let panel=featurePanel("压缩包内搜索");let query=NSSearchField();let status=NSTextField(wrappingLabelWithString:"");let scope=NSTextField(labelWithString:"");let precision=NSPopUpButton();var table:NSTableView!;let queue:OperationQueue={let q=OperationQueue();q.maxConcurrentOperationCount=1;return q}();var source:URL;let exclusions:()->[String];var results:[ZipMember]=[];var token=UUID();var timer:Timer?;let temp=FileManager.default.temporaryDirectory.appendingPathComponent("KongFetch-ZIP-"+UUID().uuidString);var busy=false;var previewPanel:NSPanel?;var quickPreview:QLPreviewView?
    init(source:URL,exclusions:@escaping()->[String]) {self.source=source;self.exclusions=exclusions;super.init();query.placeholderString="搜索 ZIP 内的文件名";query.delegate=self;precision.addItems(withTitles:["精确名称","模糊名称","名称及内部路径"]);precision.selectItem(at:1);precision.target=self;precision.action = #selector(searchNow);let pair=featureTable([("name","文件名",220),("inside","内部位置",240),("zip","所属 ZIP",260)],target:self);table=pair.0;let header=featureStack([featureButton("选择 ZIP / 文件夹…",self,#selector(choose)),precision,featureButton("搜索",self,#selector(searchNow)),featureButton("取消",self,#selector(cancel))]);let bottom=featureStack([featureButton("预览",self,#selector(previewItem)),featureButton("打开",self,#selector(openItem)),featureButton("显示所属压缩包",self,#selector(reveal))]);let stack=featureStack([header,scope,query,pair.1,status,bottom],vertical:true);featureMount(stack,in:panel);for v in [header,scope,query,pair.1,status,bottom] {v.widthAnchor.constraint(equalTo:stack.widthAnchor).isActive=true};pair.1.heightAnchor.constraint(greaterThanOrEqualToConstant:240).isActive=true;query.heightAnchor.constraint(equalToConstant:26).isActive=true;scope.lineBreakMode = .byTruncatingMiddle;scope.setContentCompressionResistancePriority(.defaultLow,for:.horizontal);scope.widthAnchor.constraint(lessThanOrEqualToConstant:720).isActive=true;scope.stringValue=source.path;status.stringValue="搜索只读取 ZIP 目录。预览或打开时才解压选中文件，最大 100 MB。" }
    func show() {panel.makeKeyAndOrderFront(nil);panel.makeFirstResponder(query)}
    func numberOfRows(in tableView:NSTableView)->Int {results.count}
    func tableView(_ tableView:NSTableView,viewFor column:NSTableColumn?,row:Int)->NSView? {let m=results[row];return featureCell(column?.identifier.rawValue == "name" ? m.basename : column?.identifier.rawValue == "inside" ? m.name : m.archive.path)}
    func controlTextDidChange(_ obj:Notification) {timer?.invalidate();timer=Timer.scheduledTimer(withTimeInterval:0.4,repeats:false) {[weak self] _ in self?.searchNow()}}
    @objc func choose() {let p=NSOpenPanel();p.canChooseDirectories=true;p.canChooseFiles=true;p.beginSheetModal(for:panel) {[weak self] response in guard let self,response == .OK,let url=p.url else{return};self.source=url;self.scope.stringValue=url.path;self.searchNow()}}
    @objc func searchNow() { guard !busy else {status.stringValue="正在处理选中文件，请稍候";return};queue.cancelAllOperations();token=UUID();let current=token,source=source,words=query.stringValue.split(whereSeparator:{$0.isWhitespace}).map(String.init),mode=SearchPrecision(rawValue:precision.indexOfSelectedItem) ?? .fuzzyName,excluded=exclusions();results=[];table.reloadData();status.stringValue="正在读取 ZIP 目录…";let operation=BlockOperation();operation.addExecutionBlock {[weak self,weak operation] in guard let operation else{return};let archives=Entry(source).directory ? scanNames([source],excluding:excluded,cancelled:{operation.isCancelled}).urls.filter{$0.pathExtension.lowercased() == "zip"} : [source];var found:[ZipMember]=[],errors:[String]=[];var searched=0
        for archive in archives {if operation.isCancelled {return};let path=archive.resolvingSymlinksInPath().path;guard !excluded.contains(where:{path == $0 || path.hasPrefix($0+"/")}) else {continue};do {let listing=try listZIP(archive);searched += 1;for member in listing.members where !member.directory && member.safe && !member.symlink {if operation.isCancelled{return};let url=URL(fileURLWithPath:"/"+member.name);if mode.score(url,words:words) != nil {found.append(member)};if found.count >= 2000 {break}}} catch {errors.append(archive.lastPathComponent+"："+error.localizedDescription)};if found.count >= 2000 {break}}
        let sorted=found.sorted {let a=mode.score(URL(fileURLWithPath:"/"+$0.name),words:words) ?? 0,b=mode.score(URL(fileURLWithPath:"/"+$1.name),words:words) ?? 0;return a == b ? $0.name.localizedStandardCompare($1.name) == .orderedAscending : a > b};DispatchQueue.main.async {guard let self,self.token == current,!operation.isCancelled else{return};self.results=sorted;self.table.reloadData();self.status.stringValue="\(found.count) 个结果 · 已读取 \(searched) 个 ZIP"+(found.count >= 2000 ? " · 最多显示 2000 项" : "")+(errors.isEmpty ? "" : "\n跳过 \(errors.count) 个压缩包："+errors.prefix(3).joined(separator:"；"));self.status.toolTip=errors.joined(separator:"\n");if !found.isEmpty {self.table.selectRowIndexes(IndexSet(integer:0),byExtendingSelection:false)}} };queue.addOperation(operation) }
    @objc func cancel() {queue.cancelAllOperations();token=UUID();status.stringValue="已取消"}
    func extract(open:Bool) {guard !busy,results.indices.contains(table.selectedRow) else{return};let member=results[table.selectedRow];busy=true;status.stringValue="正在解压选中文件…";let temp=temp;let operation=BlockOperation();operation.addExecutionBlock {[weak self,weak operation] in guard let operation else{return};do {let url=try extractZIPMember(member,to:temp,cancelled:{operation.isCancelled});DispatchQueue.main.async {guard let self else{return};self.busy=false;self.status.stringValue="已解压到临时目录："+url.path;if open {NSWorkspace.shared.open(url)} else {let p=self.previewPanel ?? featurePanel("压缩包文件预览",size:NSSize(width:720,height:560));self.previewPanel=p;if self.quickPreview == nil {let v=QLPreviewView(frame:p.contentView!.bounds,style:.normal)!;v.autoresizingMask=[.width,.height];p.contentView!.addSubview(v);self.quickPreview=v};self.quickPreview?.previewItem=url as NSURL;p.makeKeyAndOrderFront(nil)}}} catch {DispatchQueue.main.async {self?.busy=false;self?.status.stringValue=error.localizedDescription}} };queue.addOperation(operation)}
    @objc func previewItem() {extract(open:false)}
    @objc func openItem() {extract(open:true)}
    @objc func reveal() {guard results.indices.contains(table.selectedRow) else{return};NSWorkspace.shared.activateFileViewerSelecting([results[table.selectedRow].archive])}
    func stop() {timer?.invalidate();queue.cancelAllOperations();queue.waitUntilAllOperationsAreFinished();quickPreview?.previewItem=nil;previewPanel?.close();try? FileManager.default.removeItem(at:temp)}
}
final class BatchRenameController:NSObject,NSTableViewDataSource,NSTableViewDelegate,NSTextFieldDelegate {
    let panel=featurePanel("批量重命名 · 先预览再执行");var urls:[URL];var pairs:[(URL,URL)]=[];let prefix=NSTextField(),suffix=NSTextField(),find=NSTextField(),replacement=NSTextField(),start=NSTextField(string:"1"),digits=NSTextField(string:"3");let numbered=NSButton(checkboxWithTitle:"添加编号",target:nil,action:nil);let status=NSTextField(wrappingLabelWithString:"");var execute:NSButton!;var table:NSTableView!;var working=false;let perform:([(URL,URL)],@escaping(Result<Void,Error>)->Void)->Void
    init(urls:[URL],perform:@escaping([(URL,URL)],@escaping(Result<Void,Error>)->Void)->Void) {self.urls=urls;self.perform=perform;super.init();for (field,placeholder) in [(prefix,"前缀"),(suffix,"后缀"),(find,"替换文字"),(replacement,"替换为")] {field.placeholderString=placeholder;field.delegate=self;field.widthAnchor.constraint(equalToConstant:160).isActive=true};for field in [start,digits] {field.delegate=self;field.widthAnchor.constraint(equalToConstant:60).isActive=true};numbered.target=self;numbered.action = #selector(updatePreview);let a=featureStack([prefix,suffix,find,replacement]),b=featureStack([numbered,NSTextField(labelWithString:"起始"),start,NSTextField(labelWithString:"位数"),digits,featureButton("选择文件…",self,#selector(choose))]);let pair=featureTable([("old","原名称",350),("new","新名称",350)],target:self);table=pair.0;execute=featureButton("执行重命名",self,#selector(apply));let footer=featureStack([execute,featureButton("关闭",self,#selector(close))]);let stack=featureStack([NSTextField(wrappingLabelWithString:"保留文件扩展名；最多 500 项。名称冲突时停止；执行后可整批撤销。"),a,b,pair.1,status,footer],vertical:true);featureMount(stack,in:panel);pair.1.widthAnchor.constraint(equalTo:stack.widthAnchor).isActive=true;pair.1.heightAnchor.constraint(greaterThanOrEqualToConstant:240).isActive=true;status.widthAnchor.constraint(equalTo:stack.widthAnchor).isActive=true;updatePreview() }
    func show() {panel.makeKeyAndOrderFront(nil)}
    var rule:RenameRule {RenameRule(prefix:prefix.stringValue,suffix:suffix.stringValue,find:find.stringValue,replacement:replacement.stringValue,numbered:numbered.state == .on,start:start.integerValue,digits:digits.integerValue)}
    func controlTextDidChange(_ obj:Notification) {updatePreview()}
    @objc func updatePreview() {guard !working else{return};do {guard (0...1_000_000_000).contains(start.integerValue),(1...9).contains(digits.integerValue),Int(start.stringValue) != nil,Int(digits.stringValue) != nil else{throw featureError("编号起始和位数请输入有效整数")};pairs=try BatchRename.plan(urls,rule:rule);status.stringValue="已选择 \(urls.count) 项 · 将更改 \(pairs.count) 项";execute.isEnabled = !pairs.isEmpty} catch {pairs=[];execute.isEnabled=false;status.stringValue=error.localizedDescription};table?.reloadData()}
    func numberOfRows(in tableView:NSTableView)->Int {urls.count}
    func tableView(_ tableView:NSTableView,viewFor column:NSTableColumn?,row:Int)->NSView? {let url=urls[row];return featureCell(column?.identifier.rawValue == "old" ? url.lastPathComponent : rule.name(url,index:row))}
    @objc func choose() {guard !working else{return};let p=NSOpenPanel();p.canChooseDirectories=true;p.canChooseFiles=true;p.allowsMultipleSelection=true;p.beginSheetModal(for:panel) {[weak self] response in guard let self,response == .OK else{return};self.urls=p.urls.sorted{$0.path.localizedStandardCompare($1.path) == .orderedAscending};self.updatePreview()}}
    @objc func apply() {updatePreview();guard execute.isEnabled,!working else{return};let plan=pairs;working=true;execute.isEnabled=false;status.stringValue="正在执行…";perform(plan) {[weak self] result in guard let self else{return};self.working=false;switch result {case .success:self.urls=plan.map{$0.1};self.prefix.stringValue="";self.suffix.stringValue="";self.find.stringValue="";self.replacement.stringValue="";self.numbered.state = .off;self.updatePreview();self.status.stringValue="已完成 \(plan.count) 项 · 在主窗口操作菜单中可整批撤销";case .failure(let error):self.status.stringValue=error.localizedDescription;self.execute.isEnabled=false}}}
    @objc func close() {guard !working else{return};panel.close()}
}

enum OperationCommand:String,CaseIterable,Codable {
    case focus,actions,content,precision,ocr,archive,batch,undo,updates
    var title:String {switch self {case .focus:return "聚焦搜索";case .actions:return "操作菜单";case .content:return "切换名称 / 内容搜索";case .precision:return "切换名称匹配精度";case .ocr:return "OCR 管理";case .archive:return "压缩包搜索";case .batch:return "批量重命名";case .undo:return "撤销文件操作";case .updates:return "检查更新"}}
    var id:UInt32 {2000+UInt32(Self.allCases.firstIndex(of:self)!)}
}
struct OperationBinding:Codable,Equatable {
    let command:OperationCommand;var code:Int;var mods:Int;var label:String;var global:Bool;var enabled:Bool
    var valid:Bool {let mask=Int(cmdKey|optionKey|controlKey|shiftKey);return (0...127).contains(code) && ![54,55,56,57,58,59,60,61,62,63].contains(code) && mods & ~mask == 0 && mods & Int(cmdKey|optionKey|controlKey) != 0 && label.count <= 80}
    static var defaults:[OperationBinding] {zip(OperationCommand.allCases,[(37,Int(cmdKey),"⌘L",false),(40,Int(cmdKey),"⌘K",false),(19,Int(controlKey|optionKey),"⌃⌥2",true),(3,Int(controlKey|optionKey),"⌃⌥F",true),(31,Int(controlKey|optionKey),"⌃⌥O",true),(6,Int(controlKey|optionKey),"⌃⌥Z",true),(15,Int(controlKey|optionKey),"⌃⌥R",true),(6,Int(cmdKey|optionKey),"⌘⌥Z",false),(32,Int(controlKey|optionKey),"⌃⌥U",true)]).map {OperationBinding(command:$0.0,code:$0.1.0,mods:$0.1.1,label:$0.1.2,global:$0.1.3,enabled:true)} }
}
func carbonModifiers(_ flags:NSEvent.ModifierFlags)->Int { var result=0;if flags.contains(.command){result |= Int(cmdKey)};if flags.contains(.option){result |= Int(optionKey)};if flags.contains(.control){result |= Int(controlKey)};if flags.contains(.shift){result |= Int(shiftKey)};return result }
func operationKeyLabel(_ e:NSEvent)->String {var text="";for (flag,glyph) in [(NSEvent.ModifierFlags.control,"⌃"),(.option,"⌥"),(.shift,"⇧"),(.command,"⌘")] where e.modifierFlags.contains(flag) {text += glyph};let special:[UInt16:String]=[49:"空格",36:"↵",48:"Tab",53:"Esc",123:"←",124:"→",125:"↓",126:"↑",51:"⌫"];return text+(special[e.keyCode] ?? (e.charactersIgnoringModifiers?.uppercased() ?? "键\(e.keyCode)")) }
final class OperationShortcutController:NSObject,NSTableViewDataSource,NSTableViewDelegate {
    unowned let app:App;let panel=featurePanel("操作快捷键 · 支持全局触发",size:NSSize(width:720,height:520));var table:NSTableView!;let status=NSTextField(wrappingLabelWithString:"")
    init(_ app:App) {self.app=app;super.init();let pair=featureTable([("command","操作",260),("key","组合键",170),("scope","触发范围",160)],target:self);table=pair.0;table.target=self;table.doubleAction = #selector(edit);let controls=featureStack([featureButton("修改所选…",self,#selector(edit)),featureButton("启用 / 停用",self,#selector(toggle)),featureButton("恢复默认…",self,#selector(reset))]);let stack=featureStack([NSTextField(wrappingLabelWithString:"全局快捷键可在其他应用前台触发。发生占用时不会替换已生效的组合；双 Control 唤起和目录快捷键仍单独设置。"),pair.1,status,controls],vertical:true);featureMount(stack,in:panel);pair.1.widthAnchor.constraint(equalTo:stack.widthAnchor).isActive=true;pair.1.heightAnchor.constraint(greaterThanOrEqualToConstant:260).isActive=true;status.widthAnchor.constraint(equalTo:stack.widthAnchor).isActive=true;refresh() }
    func show(){refresh();panel.makeKeyAndOrderFront(nil)}
    func refresh(){table.reloadData();status.stringValue=app.operationShortcutErrors.isEmpty ? "已启用 \(app.operationHotKeys.count) 个全局操作快捷键。双击可修改组合和范围。" : app.operationShortcutErrors.joined(separator:"\n")}
    func numberOfRows(in tableView:NSTableView)->Int {OperationCommand.allCases.count}
    func tableView(_ tableView:NSTableView,viewFor column:NSTableColumn?,row:Int)->NSView? {let item=app.operationBindings[row];return featureCell(column?.identifier.rawValue == "command" ? item.command.title : column?.identifier.rawValue == "key" ? item.label : !item.enabled ? "已停用" : item.global ? "全局" : "应用内")}
    @objc func edit(){guard OperationCommand.allCases.indices.contains(table.selectedRow) else{return};var item=app.operationBindings[table.selectedRow];let alert=NSAlert();alert.messageText="设置："+item.command.title;alert.informativeText="点击输入框后按组合键。至少包含 Command、Option 或 Control。";alert.addButton(withTitle:"保存");alert.addButton(withTitle:"取消");let field=ShortcutField(string:item.label);field.isEditable=false;field.widthAnchor.constraint(equalToConstant:320).isActive=true;field.heightAnchor.constraint(equalToConstant:30).isActive=true;let global=NSButton(checkboxWithTitle:"全局触发（其他应用前台也可用）",target:nil,action:nil);global.state=item.global ? .on : .off;let message=NSTextField(wrappingLabelWithString:"");message.widthAnchor.constraint(equalToConstant:380).isActive=true;field.record={e in let candidate=OperationBinding(command:item.command,code:Int(e.keyCode),mods:carbonModifiers(e.modifierFlags),label:operationKeyLabel(e),global:global.state == .on,enabled:true);if candidate.valid {item=candidate;field.stringValue=item.label;message.stringValue=""}else{message.stringValue="请使用带修饰键的普通按键"}};app.operationRecorder={binding in item.code=binding.code;item.mods=binding.mods;item.label=binding.label;field.stringValue=item.label;message.stringValue=""};let stack=featureStack([field,global,message],vertical:true);stack.frame=NSRect(x:0,y:0,width:400,height:90);alert.accessoryView=stack;alert.beginSheetModal(for:panel) {[weak self] response in guard let self else{return};self.app.operationRecorder=nil;guard response == .alertFirstButtonReturn else{return};item.global=global.state == .on;item.enabled=true;do {try self.app.saveOperationBinding(item);self.refresh()}catch{self.status.stringValue=error.localizedDescription}};alert.window.makeFirstResponder(field)}
    @objc func toggle(){guard OperationCommand.allCases.indices.contains(table.selectedRow) else{return};var item=app.operationBindings[table.selectedRow];item.enabled.toggle();do{try app.saveOperationBinding(item);refresh()}catch{status.stringValue=error.localizedDescription}}
    @objc func reset(){let alert=NSAlert();alert.messageText="恢复默认操作快捷键？";alert.addButton(withTitle:"恢复");alert.addButton(withTitle:"取消");alert.beginSheetModal(for:panel) {[weak self] response in guard let self,response == .alertFirstButtonReturn else{return};self.app.preferences.removeObject(forKey:"operationShortcuts");self.app.registerOperationShortcuts();self.refresh()}}
}
extension App {
    var operationBindings:[OperationBinding] {let saved=(preferences.data(forKey:"operationShortcuts")).flatMap{try? JSONDecoder().decode([OperationBinding].self,from:$0)} ?? [];return OperationBinding.defaults.map { def in saved.first{$0.command == def.command && $0.valid} ?? def }}
    func bindingConflict(_ item:OperationBinding)->String? {
        guard item.valid else{return "快捷键无效"};if !item.enabled{return nil};if operationBindings.contains(where:{$0.enabled && $0.command != item.command && $0.code == item.code && $0.mods == item.mods}){return "已用于其他 KongFetch 操作"};if item.code == (preferences.object(forKey:"keyCode") as? Int ?? 49),item.mods == (preferences.object(forKey:"modifiers") as? Int ?? Int(cmdKey|optionKey)){return "已用于应用唤起"};if directoryShortcuts.contains(where:{$0["code"] as? Int == item.code && $0["mods"] as? Int == item.mods}){return "已用于目录快捷键"};if item.mods == Int(cmdKey),[0,4,7,8,9,12,13,36,43,48,51].contains(item.code){return "该组合用于编辑或窗口操作，请选择其他组合"};return nil
    }
    func registerOperationShortcuts() {for ref in operationHotKeys.values {UnregisterEventHotKey(ref)};operationHotKeys=[:];operationTargets=[:];operationShortcutErrors=[];for item in operationBindings where item.enabled {if let error=bindingConflict(item){operationShortcutErrors.append(item.command.title+"："+error);continue};if item.global {var ref:EventHotKeyRef?;if RegisterEventHotKey(UInt32(item.code),UInt32(item.mods),EventHotKeyID(signature:0x4B464554,id:item.command.id),GetApplicationEventTarget(),0,&ref) == noErr,let ref {operationHotKeys[item.command.id]=ref;operationTargets[item.command.id]=item.command}else{operationShortcutErrors.append(item.command.title+"：组合被占用，未启用")}}};updateOperationLabels() }
    func saveOperationBinding(_ item:OperationBinding)throws {if let error=bindingConflict(item){throw featureError(error)};let old=operationBindings.first{$0.command == item.command}!,sameRegistered=old.code == item.code && old.mods == item.mods && old.global && operationHotKeys[item.command.id] != nil;var candidate:EventHotKeyRef?;if item.enabled && item.global && !sameRegistered {guard RegisterEventHotKey(UInt32(item.code),UInt32(item.mods),EventHotKeyID(signature:0x4B464554,id:item.command.id),GetApplicationEventTarget(),0,&candidate) == noErr else {throw featureError("组合被其他应用占用，原快捷键保持有效")}};var bindings=operationBindings;bindings[OperationCommand.allCases.firstIndex(of:item.command)!]=item;preferences.set(try JSONEncoder().encode(bindings),forKey:"operationShortcuts");let previous=operationHotKeys.removeValue(forKey:item.command.id);if sameRegistered,item.enabled,item.global {candidate=previous} else if let previous {UnregisterEventHotKey(previous)};operationTargets.removeValue(forKey:item.command.id);if item.enabled,item.global,let candidate {operationHotKeys[item.command.id]=candidate;operationTargets[item.command.id]=item.command};operationShortcutErrors.removeAll{$0.hasPrefix(item.command.title+"：")};updateOperationLabels() }
    func updateOperationLabels(){let item=operationBindings.first{$0.command == .actions}!;actionsButton?.title="操作"+(item.enabled ? "  "+item.label : "")}
    func dispatchOperationShortcut(_ event:NSEvent)->Bool {let mods=carbonModifiers(event.modifierFlags);guard let item=operationBindings.first(where:{$0.enabled && (!$0.global || operationTargets[$0.command.id] != nil) && $0.code == Int(event.keyCode) && $0.mods == mods}),bindingConflict(item) == nil else{return false};performOperation(item.command,global:false);return true}
    func performOperation(_ command:OperationCommand,global:Bool) {if global {show()};guard window.attachedSheet == nil,!menuTracking,!(shortcutController?.panel.attachedSheet != nil),!(batchController?.working ?? false) else {status.stringValue="请先完成当前对话框或文件操作";return};switch command {case .focus:window.makeFirstResponder(search);case .actions:openActions();case .content:searchMode=searchMode == .content ? .filename : .content;updateSearchModeUI();if !search.stringValue.isEmpty{startSearch()};saveState();case .precision:precision=SearchPrecision(rawValue:(precision.rawValue+1)%3)!;searchMode = .filename;updateSearchModeUI();if !search.stringValue.isEmpty{startSearch()};saveState();case .ocr:openOCRManager();case .archive:openArchiveSearch();case .batch:openBatchRename();case .undo:undoFileOperation();case .updates:checkForUpdates()} }
    @objc func openOperationShortcuts(){if shortcutController == nil {shortcutController=OperationShortcutController(self)};shortcutController?.show()}
    @objc func openOCRManager(){if ocrController == nil {ocrController=OCRPanelController(ocrManager)};ocrController?.show()}
    @objc func openArchiveSearch(){archiveController?.stop();archiveController?.panel.close();archiveController=ArchiveSearchController(source:selected?.url.pathExtension.lowercased() == "zip" ? selected!.url : scopeAll ? FileManager.default.homeDirectoryForCurrentUser : folder,exclusions:{[weak self] in self?.excludedRoots ?? []});archiveController?.show()}
    var renameJournalDirectory:URL {FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent("Library/Application Support/KongFetch/RenameRecovery")}
    @objc func openBatchRename(){guard !fileOperationBusy else{return};batchController?.panel.close();batchController=BatchRenameController(urls:selectedURLs.sorted{$0.path.localizedStandardCompare($1.path) == .orderedAscending},perform:{[weak self] pairs,completion in self?.performBatchRename(pairs,completion:completion)});batchController?.show()}
    func performBatchRename(_ pairs:[(URL,URL)],completion:@escaping(Result<Void,Error>)->Void){guard !fileOperationBusy else{completion(.failure(featureError("已有文件操作正在执行")));return};fileOperationBusy=true;let journals=renameJournalDirectory;let identities=pairs.map{fileIdentity($0.0)};fileOperationQueue.addOperation {[weak self] in do {try BatchRename.execute(pairs,journalDirectory:journals);DispatchQueue.main.async {guard let self else{return};self.fileOperationBusy=false;self.fileUndos.append(FileUndo(title:"撤销整批重命名（\(pairs.count) 项）",reverse:{[weak self] in guard let self,!self.fileOperationBusy else{throw featureError("请等待当前文件操作完成")};guard pairs.enumerated().allSatisfy({fileIdentity($0.element.1) == identities[$0.offset]}) else{throw featureError("文件已被移动或替换，停止整批撤销")};try BatchRename.execute(pairs.map{($0.1,$0.0)},journalDirectory:journals);self.refreshAfterFileOperation();self.status.stringValue="已撤销整批重命名"}));if self.fileUndos.count > 20 {self.fileUndos.removeFirst()};self.refreshAfterFileOperation();completion(.success(()))}}catch{DispatchQueue.main.async {self?.fileOperationBusy=false;completion(.failure(error))}}} }
    @objc func recoverBatchRename(){let files=(try? FileManager.default.contentsOfDirectory(at:renameJournalDirectory,includingPropertiesForKeys:nil))?.filter{$0.pathExtension == "json"} ?? [];guard !files.isEmpty else{status.stringValue="没有待恢复的批量重命名记录";return};let alert=NSAlert();alert.messageText="恢复未完成的批量重命名";alert.informativeText="按文件身份恢复原名称；遇到被占用的名称会停止，不会覆盖文件。";alert.addButton(withTitle:"预览恢复");alert.addButton(withTitle:"取消");let picker=NSPopUpButton(frame:NSRect(x:0,y:0,width:400,height:28));picker.addItems(withTitles:files.map(\.lastPathComponent));alert.accessoryView=picker;alert.beginSheetModal(for:window) {[weak self] response in guard let self,response == .alertFirstButtonReturn else{return};let journal=files[picker.indexOfSelectedItem];do{let pairs=try BatchRename.recoveryPairs(journal);try BatchRename.validate(pairs);let confirm=NSAlert();confirm.messageText="恢复 \(pairs.count) 项原名称？";confirm.informativeText=pairs.prefix(12).map{$0.0.lastPathComponent+" → "+$0.1.lastPathComponent}.joined(separator:"\n");confirm.addButton(withTitle:"恢复");confirm.addButton(withTitle:"取消");confirm.beginSheetModal(for:self.window){response in guard response == .alertFirstButtonReturn else{return};self.performBatchRename(pairs){result in switch result{case .success:try? FileManager.default.removeItem(at:journal);self.status.stringValue="已恢复原名称";case .failure(let error):self.status.stringValue=error.localizedDescription}}}}catch{self.status.stringValue=error.localizedDescription}} }
    func add31Actions(_ menu:NSMenu){for (title,action) in [("OCR 管理…",#selector(openOCRManager)),("搜索压缩包内部…",#selector(openArchiveSearch)),("批量重命名（先预览）…",#selector(openBatchRename)),("恢复未完成的批量重命名…",#selector(recoverBatchRename)),("操作快捷键（支持全局）…",#selector(openOperationShortcuts)),("检查 GitHub 更新…",#selector(checkForUpdates)),("回退到备份版本…",#selector(rollbackUpdate))] {let item=NSMenuItem(title:title,action:action,keyEquivalent:"");item.target=self;menu.addItem(item)};menu.addItem(.separator())}
    func resetOCRPositions(){ocrPositions=[];ocrImageView.image=nil;ocrImageView.boxes=[];ocrImageView.isHidden=true}
    func showOCRPositions(_ entry:Entry,record:OCRRecord,words:[String])->Bool {guard searchMode == .content,let spans=record.spans else{return false};let document=entry.url.pathExtension.lowercased() == "pdf" ? PDFDocument(url:entry.url) : nil;let boxes=spans.flatMap {span -> [(Int,CGRect)] in if span.glyphs.isEmpty,let page=document?.page(at:span.page),let text=page.string,text.count > 20 {return matchRanges(text,words:words,allowWhitespace:true).compactMap{range in page.selection(for:range).map{(span.page,normalizedPDFBox($0.bounds(for:page),on:page))}}};return span.matches(words).map{(span.page,$0)}};guard !boxes.isEmpty else{return false};ocrPositions=Array(boxes.prefix(500));matchIndex=0;pdfLimited=record.limited || boxes.count > 500;evidenceLabel.attributedStringValue=highlightExcerpt("本地 OCR · "+excerptText(record.text,words:words,allowWhitespace:true));evidenceLabel.toolTip=String(record.text.prefix(4000));if let document {pdfView.document=document;pdfView.isHidden=false;preview.isHidden=true;for (index,rect) in ocrPositions {if let page=document.page(at:index){let annotation=PDFAnnotation(bounds:pdfBox(rect,on:page),forType:.square,withProperties:nil);annotation.color=NSColor.systemOrange;annotation.interiorColor=NSColor.systemYellow.withAlphaComponent(0.2);page.addAnnotation(annotation)}}}else if let image=NSImage(contentsOf:entry.url){ocrImageView.image=image;ocrImageView.boxes=ocrPositions.map{$0.1};ocrImageView.isHidden=false;preview.isHidden=true}else{ocrPositions=[];return false};updateOCRPosition();return true }
    func updateOCRPosition(){let count=ocrPositions.count;guard count > 0 else{return};matchIndex=(matchIndex+count)%count;let position=ocrPositions[matchIndex];previousMatch.isEnabled=count > 1;nextMatch.isEnabled=count > 1;if let page=pdfView.document?.page(at:position.0){pdfView.go(to:PDFDestination(page:page,at:pdfBox(position.1,on:page).origin))}else{ocrImageView.boxes=[position.1]};matchLabel.stringValue="OCR \(matchIndex+1) / \(count) · 第 \(position.0+1) 页"+(pdfLimited ? " · 部分页面" : "")}
}

final class UpdateStatusController:NSObject {
    let panel=featurePanel("KongFetch 更新",size:NSSize(width:680,height:420));let label=NSTextField(wrappingLabelWithString:"");let progress=NSProgressIndicator();var cancelAction:(()->Void)?
    override init(){super.init();progress.isIndeterminate=false;progress.minValue=0;progress.maxValue=1;let stack=featureStack([label,progress,featureButton("取消下载",self,#selector(cancel))],vertical:true);featureMount(stack,in:panel);label.widthAnchor.constraint(equalTo:stack.widthAnchor).isActive=true;progress.widthAnchor.constraint(equalTo:stack.widthAnchor).isActive=true;label.heightAnchor.constraint(greaterThanOrEqualToConstant:180).isActive=true}
    func show(_ text:String){label.stringValue=text;panel.makeKeyAndOrderFront(nil)}
    @objc func cancel(){cancelAction?()}
}
extension App {
    var updatesDirectory:URL {FileManager.default.homeDirectoryForCurrentUser.appendingPathComponent("Library/Application Support/KongFetch/Updates")}
    @objc func checkForUpdates(){guard !checkingUpdate,updateDownload == nil else{status.stringValue="更新检查或下载正在进行";updateStatusController?.panel.makeKeyAndOrderFront(nil);return};checkingUpdate=true;status.stringValue="正在检查 GitHub 更新…";var request=URLRequest(url:URL(string:"https://raw.githubusercontent.com/kongxiangruihello/KongFetch/main/dist/latest.json")!);request.cachePolicy = .reloadIgnoringLocalCacheData;request.timeoutInterval=20;updateTask=URLSession.shared.dataTask(with:request){[weak self] data,response,error in
        let result:Result<UpdateManifest,Error>;do{if let error {throw error};guard let http=response as? HTTPURLResponse,http.statusCode == 200,let url=http.url,trustedUpdateURL(url),let data,data.count < 100000 else{throw featureError("未能读取更新清单，请稍后重试")};let manifest=try JSONDecoder().decode(UpdateManifest.self,from:data);try manifest.validate();result = .success(manifest)}catch{result = .failure(error)}
        DispatchQueue.main.async {guard let self else{return};self.checkingUpdate=false;self.updateTask=nil;switch result {case .failure(let error):self.status.stringValue="检查更新失败："+error.localizedDescription;case .success(let manifest):self.reviewUpdate(manifest)}}};updateTask?.resume() }
    func reviewUpdate(_ manifest:UpdateManifest){let current=Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "3.1",build=Int(Bundle.main.infoDictionary?["CFBundleVersion"] as? String ?? "27") ?? 27;guard versionOrder(manifest.version,current) == .orderedDescending || (versionOrder(manifest.version,current) == .orderedSame && manifest.build > build) else{status.stringValue="KongFetch \(current) 已是最新版本";return};let os=ProcessInfo.processInfo.operatingSystemVersion;guard versionOrder(manifest.minimumSystemVersion,"\(os.majorVersion).\(os.minorVersion).\(os.patchVersion)") != .orderedDescending else{status.stringValue="新版需要 macOS "+manifest.minimumSystemVersion;return};let alert=NSAlert();alert.messageText="发现 KongFetch "+manifest.version;alert.informativeText=manifest.notes.joined(separator:"\n")+"\n\n下载自 KongFetch 的 GitHub 仓库，安装前检查大小与 SHA-256；替换应用前保留旧版备份。";alert.addButton(withTitle:"下载并检查");alert.addButton(withTitle:"稍后");alert.beginSheetModal(for:window){[weak self] response in if response == .alertFirstButtonReturn {self?.downloadUpdate(manifest)}} }
    func downloadUpdate(_ manifest:UpdateManifest){guard updateDownload == nil else{return};let directory=updatesDirectory.appendingPathComponent(UUID().uuidString),zip=directory.appendingPathComponent("KongFetch.zip");let controller=UpdateStatusController();updateStatusController=controller;controller.show("正在下载 KongFetch "+manifest.version+"…");let downloader=UpdateDownload(manifest:manifest,destination:zip,progress:{[weak controller] value in controller?.progress.doubleValue=value;controller?.label.stringValue="下载进度：\(Int(value*100))%"},completion:{[weak self,weak controller] result in guard let self else{return};self.updateDownload=nil;controller?.cancelAction=nil;switch result {case .failure(let error):controller?.label.stringValue="下载未完成："+error.localizedDescription;self.status.stringValue=error.localizedDescription;case .success(let url):controller?.label.stringValue="校验通过，正在检查应用签名与版本…";self.fileOperationQueue.addOperation {do{let app=try ApplicationInstaller.prepare(url,manifest:manifest,directory:directory.appendingPathComponent("Extracted"));DispatchQueue.main.async {controller?.panel.close();self.offerInstallation(app)}}catch{DispatchQueue.main.async {controller?.label.stringValue="安装包检查失败："+error.localizedDescription;self.status.stringValue=error.localizedDescription}}}}});updateDownload=downloader;controller.cancelAction={[weak downloader] in downloader?.cancel()};downloader.start() }
    func offerInstallation(_ source:URL){let target=Bundle.main.bundleURL,approved=["/Applications/KongFetch.app",NSHomeDirectory()+"/Applications/KongFetch.app"];guard approved.contains(target.path) else{NSWorkspace.shared.activateFileViewerSelecting([source]);status.stringValue="新版已校验，请将 KongFetch.app 拖入应用程序文件夹安装";return};let alert=NSAlert();alert.messageText="安装已校验的 KongFetch？";alert.informativeText="当前应用将退出并重新打开。旧版会备份在本机，可从操作菜单回退。更新后检查输入监控权限和双 Control 唤起。";alert.addButton(withTitle:"备份并安装");alert.addButton(withTitle:"稍后");alert.beginSheetModal(for:window){[weak self] response in guard let self,response == .alertFirstButtonReturn else{return};self.launchInstaller(source,target:target)} }
    func launchInstaller(_ source:URL,target:URL){do{_ = try ApplicationInstaller.version(source);let fm=FileManager.default;guard fm.isWritableFile(atPath:target.deletingLastPathComponent().path) else{throw featureError("当前应用目录需要管理员权限，请手动安装已校验的应用")};let helperDir=updatesDirectory.appendingPathComponent("Helper-"+UUID().uuidString);try fm.createDirectory(at:helperDir,withIntermediateDirectories:true);let helper=helperDir.appendingPathComponent("KongFetch-helper");try fm.copyItem(at:source.appendingPathComponent("Contents/MacOS/KongFetch"),to:helper);try fm.setAttributes([.posixPermissions:0o700],ofItemAtPath:helper.path);let process=Process();process.executableURL=helper;process.arguments=["--install-helper",String(ProcessInfo.processInfo.processIdentifier),source.path,target.path,updatesDirectory.appendingPathComponent("Backups").path,updatesDirectory.appendingPathComponent("last-result.json").path];process.standardOutput=FileHandle.nullDevice;process.standardError=FileHandle.nullDevice;try process.run();NSApp.terminate(nil)}catch{status.stringValue="自动安装未开始："+error.localizedDescription;NSWorkspace.shared.activateFileViewerSelecting([source])} }
    @objc func rollbackUpdate(){let root=updatesDirectory.appendingPathComponent("Backups");let backups=((try? FileManager.default.contentsOfDirectory(at:root,includingPropertiesForKeys:[.contentModificationDateKey])) ?? []).filter{$0.pathExtension == "app"}.sorted{(Entry($0).modified ?? .distantPast) > (Entry($1).modified ?? .distantPast)};guard !backups.isEmpty else{status.stringValue="尚无更新备份";return};let alert=NSAlert();alert.messageText="选择要回退的 KongFetch";alert.informativeText="回退前也会备份当前版本。偏好设置与文件缓存保留，授权可能需要重新检查。";alert.addButton(withTitle:"检查并回退");alert.addButton(withTitle:"取消");let picker=NSPopUpButton(frame:NSRect(x:0,y:0,width:440,height:28));picker.addItems(withTitles:backups.map(\.lastPathComponent));alert.accessoryView=picker;alert.beginSheetModal(for:window){[weak self] response in guard let self,response == .alertFirstButtonReturn else{return};self.offerInstallation(backups[picker.indexOfSelectedItem])} }
    func reportLastUpdate(){let url=updatesDirectory.appendingPathComponent("last-result.json");guard let data=try? Data(contentsOf:url),data.count < 100000,let report=try? JSONSerialization.jsonObject(with:data) as? [String:Any],let modified=Entry(url).modified,preferences.object(forKey:"lastUpdateReport") as? Date != modified else{return};preferences.set(modified,forKey:"lastUpdateReport");status.stringValue=report["message"] as? String ?? "更新处理完成";let alert=NSAlert();alert.messageText=(report["ok"] as? Bool == true) ? "KongFetch 更新完成" : "更新未完成，保留原版本";alert.informativeText=(report["message"] as? String ?? "")+"\n当前输入监控："+(CGPreflightListenEventAccess() ? "已允许" : "需检查")+"。可打开唤起诊断测试窗口和输入焦点。";alert.addButton(withTitle:"唤起诊断");alert.addButton(withTitle:"完成");alert.beginSheetModal(for:window){[weak self] response in if response == .alertFirstButtonReturn {self?.wakeDiagnostics()}} }
}

extension App {
    func make31Fixture()->URL {var root=URL(fileURLWithPath:FileManager.default.currentDirectoryPath).appendingPathComponent("KongFetch-31-QA-"+UUID().uuidString);try! FileManager.default.createDirectory(at:root,withIntermediateDirectories:true);root=physicalURL(root);previewFixture=root;qaSuite="com.kongfetch.qa31."+UUID().uuidString;preferences=UserDefaults(suiteName:qaSuite!)!;restoringState=true;catalogStore=CatalogStore(root.appendingPathComponent(".index"));ocrStore=OCRStore(root.appendingPathComponent(".ocr"));preferences.set(false,forKey:"adaptiveResources");scopeAll=false;folder=root;return root}
    func makeOCR31(_ url:URL,text:String){let image=NSImage(size:NSSize(width:1500,height:350));image.lockFocus();NSColor.white.setFill();NSRect(x:0,y:0,width:1500,height:350).fill();(text as NSString).draw(in:NSRect(x:70,y:100,width:1360,height:160),withAttributes:[.font:NSFont.systemFont(ofSize:64),.foregroundColor:NSColor.black]);image.unlockFocus();let bitmap=NSBitmapImageRep(data:image.tiffRepresentation!)!;try! bitmap.representation(using:.png,properties:[:])!.write(to:url)}
    func release31UI(){let root=make31Fixture();try! FileManager.default.createDirectory(at:root.appendingPathComponent("乐乐"),withIntermediateDirectories:true);try! Data("preview".utf8).write(to:root.appendingPathComponent("年度合同.txt"));try! Data("preview".utf8).write(to:root.appendingPathComponent("乐乐/资料.txt"));let image=root.appendingPathComponent("扫描合同.png");makeOCR31(image,text:"Annual Contract 2026 乐乐");searchMode = .filename;precision = .fuzzyName;updateSearchModeUI();search.stringValue="乐乐";startSearch();registerOperationShortcuts();ocrManager.add(root);show()}
    func release31Check(){let root=make31Fixture();let fm=FileManager.default
        let exact=root.appendingPathComponent("乐乐"),partial=root.appendingPathComponent("乐乐资料.txt"),noise=root.appendingPathComponent("乐乐/资料.txt");try! fm.createDirectory(at:exact,withIntermediateDirectories:true);try! Data([1]).write(to:partial);try! Data([1]).write(to:noise)
        precondition(SearchPrecision.exactName.score(exact,words:["乐乐"]) != nil && SearchPrecision.exactName.score(partial,words:["乐乐"]) == nil);precondition(SearchPrecision.fuzzyName.score(noise,words:["乐乐"]) == nil && SearchPrecision.withPath.score(noise,words:["乐乐"]) != nil);precondition(SearchPrecision.fuzzyName.score(exact,words:["lele"]) != nil);precision = .exactName;search.stringValue="乐乐";localMatches=[Entry(noise),Entry(partial),Entry(exact)];renderSearchResults();precondition(entries.map(\.url) == [exact]);precision = .fuzzyName;renderSearchResults();precondition(entries.count == 2 && entries.first?.url == exact);stopQuery();print("PASS 3.1 search precision: exact/fuzzy/path, pinyin and parent-path noise")
        do {
            let a=root.appendingPathComponent("A.txt"),b=root.appendingPathComponent("B.txt");try Data("alpha".utf8).write(to:a);try Data("beta".utf8).write(to:b);let journals=root.appendingPathComponent(".journals");try BatchRename.execute([(a,b),(b,a)],journalDirectory:journals);precondition((try? String(contentsOf:a,encoding:.utf8)) == "beta");try BatchRename.execute([(b,a),(a,b)],journalDirectory:journals);precondition((try? String(contentsOf:a,encoding:.utf8)) == "alpha");do{_ = try BatchRename.plan([a,b],rule:RenameRule(find:"A",replacement:"B"));preconditionFailure("collision accepted")}catch{};let p=try BatchRename.plan([a,b],rule:RenameRule(prefix:"2026-",numbered:true,start:7,digits:3));precondition(p[0].1.lastPathComponent == "2026-A-007.txt");let identity=fileIdentity(a)!,tmp=root.appendingPathComponent(".crash-A"),journal=journals.appendingPathComponent("crash.json");try JSONEncoder().encode(RenameJournal(items:[RenamePair(original:a.path,target:b.path,identity:identity,temporary:tmp.path)],completed:false)).write(to:journal);try fm.moveItem(at:a,to:tmp);let recovery=try BatchRename.recoveryPairs(journal);try BatchRename.execute(recovery,journalDirectory:journals);precondition(fm.fileExists(atPath:a.path));try fm.removeItem(at:journal)
            print("PASS 3.1 batch rename: preview numbering, collision refusal, swap, whole-batch undo and interrupted recovery")
            let zipSource=root.appendingPathComponent("ZIP 源");try fm.createDirectory(at:zipSource,withIntermediateDirectories:true);let literal=zipSource.appendingPathComponent("乐乐[2026]*?.txt");let content=String(repeating:"Annual Contract 2026\n",count:2000);try Data(content.utf8).write(to:literal);let archive=root.appendingPathComponent("合同.zip");try runTool("/usr/bin/zip",["-j",archive.path,literal.path]);let listing=try listZIP(archive);precondition(listing.members.count == 1 && listing.members[0].name == literal.lastPathComponent);let extracted=try extractZIPMember(listing.members[0],to:root.appendingPathComponent(".extracted"),cancelled:{false});precondition((try? String(contentsOf:extracted,encoding:.utf8)) == content);let unsafe=ZipMember(archive:archive,name:"../escape.txt",size:1,compressed:1,crc:0,method:0,flags:0,attributes:0,localOffset:0);precondition(!unsafe.safe);do{_ = try extractZIPMember(unsafe,to:root,cancelled:{false});preconditionFailure("unsafe ZIP accepted")}catch{};print("PASS 3.1 ZIP: Chinese literal wildcard filename, deflate extraction, contents and traversal refusal")
            registerOperationShortcuts();let initial=operationBindings.first{$0.command == .ocr}!;precondition(operationTargets[initial.command.id] == .ocr);try saveOperationBinding(initial);precondition(operationHotKeys[initial.command.id] != nil);let conflict=OperationBinding(command:.archive,code:initial.code,mods:initial.mods,label:initial.label,global:true,enabled:true);do{try saveOperationBinding(conflict);preconditionFailure("shortcut collision accepted")}catch{};precondition(operationBindings.first{$0.command == .archive} != conflict);var custom=initial;custom.code=35;custom.mods=Int(controlKey|optionKey|shiftKey);custom.label="⌃⌥⇧P";try saveOperationBinding(custom);precondition(operationTargets[custom.command.id] == .ocr);var local=custom;local.global=false;try saveOperationBinding(local);precondition(operationHotKeys[local.command.id] == nil);try saveOperationBinding(initial);print("PASS 3.1 operation shortcuts: global Carbon registration, edit, local/global transition, persistence and conflicts")
            let field=ShortcutField(frame:NSRect(x:0,y:0,width:200,height:30));field.isEditable=false;window.contentView!.addSubview(field);precondition(window.makeFirstResponder(field) && window.firstResponder === field);var captured=false;field.record={event in captured=event.keyCode == 35 && carbonModifiers(event.modifierFlags) == Int(controlKey|optionKey|shiftKey)};let event=NSEvent.keyEvent(with:.keyDown,location:.zero,modifierFlags:[.control,.option,.shift],timestamp:0,windowNumber:window.windowNumber,context:nil,characters:"P",charactersIgnoringModifiers:"p",isARepeat:false,keyCode:35)!;field.keyDown(with:event);precondition(captured);field.removeFromSuperview();window.makeFirstResponder(search);print("PASS 3.1 shortcut recorder: read-only field accepts keyboard focus and records the full combination")

            let pageImage=NSImage(size:NSSize(width:400,height:600));pageImage.lockFocus();NSColor.white.setFill();NSRect(x:0,y:0,width:400,height:600).fill();pageImage.unlockFocus();let page=PDFPage(image:pageImage)!;let rect=CGRect(x:0.1,y:0.2,width:0.3,height:0.1);for angle in [0,90,180,270]{page.rotation=angle;let mapped=pdfBox(rect,on:page);precondition(page.bounds(for:.mediaBox).contains(mapped) && mapped.width > 0 && mapped.height > 0)}
            let source=root.appendingPathComponent("new/KongFetch.app"),target=root.appendingPathComponent("installed/KongFetch.app"),backups=root.appendingPathComponent("backups");try fm.createDirectory(at:source.deletingLastPathComponent(),withIntermediateDirectories:true);try fm.createDirectory(at:target.deletingLastPathComponent(),withIntermediateDirectories:true);try fm.copyItem(at:Bundle.main.bundleURL,to:source);try fm.copyItem(at:Bundle.main.bundleURL,to:target);let plist=source.appendingPathComponent("Contents/Info.plist");var values=try PropertyListSerialization.propertyList(from:Data(contentsOf:plist),format:nil) as! [String:Any];values["CFBundleShortVersionString"]="3.2";values["CFBundleVersion"]="28";try PropertyListSerialization.data(fromPropertyList:values,format:.xml,options:0).write(to:plist);try runTool("/usr/bin/codesign",["--force","--deep","--sign","-",source.path]);let package=root.appendingPathComponent("update.zip");try runTool("/usr/bin/ditto",["-c","-k","--keepParent",source.path,package.path]);let manifest=UpdateManifest(version:"3.2",build:28,minimumSystemVersion:"13.0",notes:["QA"],zipURL:"https://raw.githubusercontent.com/kongxiangruihello/KongFetch/main/dist/KongFetch-3.2-Mac.zip",sha256:try sha256File(package),bytes:Int(Entry(package).size));let prepared=try ApplicationInstaller.prepare(package,manifest:manifest,directory:root.appendingPathComponent("update-expanded"));let backup=try ApplicationInstaller.install(prepared,target:target,backupDirectory:backups);precondition((try? ApplicationInstaller.version(target)) == "3.2" && (try? ApplicationInstaller.version(backup)) == "3.1");_ = try ApplicationInstaller.install(backup,target:target,backupDirectory:backups);precondition((try? ApplicationInstaller.version(target)) == "3.1");precondition(!trustedUpdateURL(URL(string:"https://example.com/KongFetch.zip")!));try Data([1]).write(to:package);do{_ = try ApplicationInstaller.prepare(package,manifest:manifest,directory:root.appendingPathComponent("bad-expanded"));preconditionFailure("invalid update hash accepted")}catch{};print("PASS 3.1 updater: SHA-256/source/signature/version, temp installation, old-app backup, rollback and tamper refusal")
        }catch{print("FAIL 3.1: "+error.localizedDescription);fflush(stdout);exit(1)}
        // Run real Vision recognition and FSEvents updates in a temporary, isolated OCR store.
        let image=root.appendingPathComponent("OCR-Contract.png");makeOCR31(image,text:"Annual Contract 2026 乐乐");let scannedPDF=root.appendingPathComponent("OCR-Pages.pdf");let document=PDFDocument();let first=PDFPage(image:NSImage(contentsOf:image)!)!,second=PDFPage(image:NSImage(contentsOf:image)!)!;second.rotation=90;document.insert(first,at:0);document.insert(second,at:1);precondition(document.write(to:scannedPDF));ocrManager.setPaused(true);ocrManager.add(root);let deadline=Date().addingTimeInterval(100);var phase=0,initialModified:Date?;var restoredManager:OCRManager?;let moved=root.appendingPathComponent("OCR-Moved.png");let timer=Timer.scheduledTimer(withTimeInterval:0.25,repeats:true){[weak self] timer in guard let self else{return};if Date() > deadline{print("FAIL 3.1 OCR auto-update phase \(phase): "+self.ocrManager.summary+" expected="+image.path+" keys="+self.ocrManager.jobs.keys.joined(separator:" | "));fflush(stdout);exit(1)}
            switch phase {case 0:if self.ocrManager.jobs.values.contains(where:{$0.path.hasSuffix("/OCR-Contract.png") && $0.state == "等待"}) {precondition(self.ocrManager.records[image.path] == nil);self.ocrManager.setPaused(false);phase=1}
            case 1:if let record=self.ocrManager.records[image.path],record.isCurrent(){precondition(normalized(record.text).contains("contract"));let boxes=record.spans?.flatMap{$0.matches(["Contract"])} ?? [];precondition(!boxes.isEmpty && boxes.allSatisfy{$0.width > 0 && $0.height > 0});precondition(record.spans?.contains(where:{!$0.glyphs.isEmpty}) == true);self.searchMode = .content;self.search.stringValue="Contract";self.entries=[Entry(image)];self.table.reloadData();self.table.selectRowIndexes(IndexSet(integer:0),byExtendingSelection:false);self.prepareEvidence(Entry(image));precondition(!self.ocrPositions.isEmpty && !self.ocrImageView.isHidden);initialModified=record.modified;self.ocrManager.setPaused(true);self.makeOCR31(image,text:"Revised Agreement 2027 乐乐");phase=2}
            case 2:if self.ocrManager.jobs[image.path]?.state == "等待" {precondition(self.ocrManager.records[image.path]?.modified == initialModified);self.ocrManager.setPaused(false);phase=3}
            case 3:if let record=self.ocrManager.records[image.path],record.isCurrent(),normalized(record.text).contains("agreement"){try! fm.moveItem(at:image,to:moved);phase=4}
            case 4:if let record=self.ocrManager.records[moved.path],record.isCurrent(),let pdfRecord=self.ocrManager.records[scannedPDF.path],pdfRecord.isCurrent(){precondition(normalized(record.text).contains("agreement"));precondition(self.ocrManager.records[image.path] == nil || self.ocrManager.records[image.path]?.isCurrent() == false);self.searchMode = .content;self.search.stringValue="Contract";self.entries=[Entry(scannedPDF)];self.table.reloadData();self.table.selectRowIndexes(IndexSet(integer:0),byExtendingSelection:false);self.prepareEvidence(Entry(scannedPDF));precondition(!self.ocrPositions.isEmpty && !self.pdfView.isHidden && self.ocrPositions.contains(where:{$0.0 == 1}));self.matchIndex=self.ocrPositions.count-1;self.updateOCRPosition();precondition(self.pdfView.document?.index(for:self.pdfView.currentPage!) == 1);self.ocrManager.stop(wait:true);restoredManager=OCRManager(store:self.ocrStore,preferences:self.preferences,excludes:{[]},adaptive:{false},changed:{_,_ in});restoredManager?.start();phase=5}
            case 5:if let restoredManager,restoredManager.records[moved.path]?.isCurrent() == true,!restoredManager.roots.isEmpty {restoredManager.stop(wait:true);timer.invalidate();print("PASS 3.1 OCR: real Vision word boxes, image/PDF page positioning, pause/resume, file modifications/moves via FSEvents, persisted folders/cache reload");print("PASS release 3.1 checks");fflush(stdout);self.stopQuery();NSApp.terminate(nil)}
            default:break}
        };RunLoop.main.add(timer,forMode:.common)
    }
}

func verifyPackageCLI(_ args:[String])throws {
    guard args.count == 4 else {throw featureError("需要 ZIP 路径和更新清单路径")};let manifest=try JSONDecoder().decode(UpdateManifest.self,from:Data(contentsOf:URL(fileURLWithPath:args[3]))),root=FileManager.default.temporaryDirectory.appendingPathComponent("KongFetch-package-check-"+UUID().uuidString);defer {try? FileManager.default.removeItem(at:root)};let app=try ApplicationInstaller.prepare(URL(fileURLWithPath:args[2]),manifest:manifest,directory:root);print("PASS packaged update: SHA-256, archive paths, universal app signature, version "+(try ApplicationInstaller.version(app)))
}
func verifyDownloadCLI(_ args:[String])throws {
    guard args.count == 3 else {throw featureError("需要更新清单路径")};let manifest=try JSONDecoder().decode(UpdateManifest.self,from:Data(contentsOf:URL(fileURLWithPath:args[2])));try manifest.validate();let root=FileManager.default.temporaryDirectory.appendingPathComponent("KongFetch-download-check-"+UUID().uuidString);defer {try? FileManager.default.removeItem(at:root)};var result:Result<URL,Error>?,bucket = -1;let downloader=UpdateDownload(manifest:manifest,destination:root.appendingPathComponent("download.zip"),progress:{value in let next=Int(value*10);if next != bucket {bucket=next;print("Download check: \(next*10)%");fflush(stdout)}},completion:{result=$0});downloader.start();let deadline=Date().addingTimeInterval(90);while result == nil && Date() < deadline {RunLoop.main.run(until:Date().addingTimeInterval(0.1))};guard let result else {downloader.cancel();throw featureError("下载验证超时")};let zip=try result.get();let app=try ApplicationInstaller.prepare(zip,manifest:manifest,directory:root.appendingPathComponent("expanded"));print("PASS GitHub download/update check: size, SHA-256, signature, version "+(try ApplicationInstaller.version(app)))
}
